### ISSUE TITLE
Incorrect permissions for dependent submodules

### ISSUE THREAD

**Issue by thclark** [g3w-suite/g3w-admin#10]
Hi folks,

I'm just trying to stand up a g3w-admin server for a client of mine who I think could use your platform effectively, and I can't get things off the ground as the submodules hosted on bitbucket are private (i.e. I can't run the `docker/install-modules.sh` script due to access violations).
```
sh docker/install-modules.sh
```
> docker/install-modules.sh: line 3: declare: -A: invalid option
> declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
> Cloning into '/Users/thc29/Source/octue/windquest/g3w_admin/0'...
> remote: Forbidden
> fatal: unable to access 'https://bitbucket.org/gis3w/g3w-admin-iternet.git/': The requested URL returned error: 403
> fatal: clone of 'https://bitbucket.org/gis3w/g3w-admin-iternet.git' into submodule path '/Users/thc29/Source/octue/windquest/g3w_admin/0' failed

Is this a permanent thing thats a policy of g3w-suite, or an accident?

Related issue which also causes a lot of hassle is the configuration of submodules - the submodules folders should not be `.gitignored` as this prevents the parent repo from determining what version of the submodule is `.gitlink`ed (see [here](https://stackoverflow.com/questions/7912022/do-you-ignore-a-git-submodule-in-your-gitignore-or-commit-it-to-your-repo)).

Thanks for any comments!

Tom

**Comment by wlorenzetti** [comment]
Hi Tom,
sorry but docker 'section' is old and not correct. You don't use it please.
Private repositories are a policy of Gis3W, not every submodules are open.
For submodules your right It'll be gitgnored in the future.
I think you try to deploy 'master' branch, but at the moment I suggest you to try 'dev' branch that supports QGIS3.
If you have other questions, you are welcome.
W
