### ISSUE TITLE
Editing: upload multimedia

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-admin#100]
New project: http://64.225.77.93:8080/it/map/g3w-suite-demo/qdjango/8/

Layer on SpatiaLite

If you try ti add or moduify a feature of the two layer, the buttom to upload a file doesn't work...

It work on Building managemente project

**Comment by wlorenzetti** [comment]
@leolami I just tried but it seams works fine:
![Schermata da 2020-05-27 12-50-56](https://user-images.githubusercontent.com/196809/83010620-d451a080-a018-11ea-95c0-7494bfe4c056.png)

**Comment by leolami** [comment]
It works on Chrome
It doesn't work on Firefox

Can you retry?

**Comment by wlorenzetti** [comment]
I did that on firefox.. on Ubuntu.

**Comment by leolami** [comment]
Ok, now it works...I don't know...this morning it doesn't work...
