### ISSUE TITLE
Join 1:1

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-admin#104]
In this project http://64.225.77.93:8080/en/map/g3w-suite-demo/qdjango/3/

I add a alphanumeric table (**JOIN**) joined to the **Buildings** layer

I can't see the fields of JOIN table quering poligons (TAB Technical data - Data join 1:1)

The edit doesn't start....

**Comment by leolami** [comment]
[test_formati_vari.zip](https://github.com/g3w-suite/g3w-admin/files/4695167/test_formati_vari.zip)

**Comment by leolami** [comment]
Join data problem visualization with Geopackage data
Can you verify?
http://64.225.77.93:8080/it/map/g3w-suite-demo/qdjango/14/

**Comment by wlorenzetti** [comment]
@leolami I think problem is linked to Geopackage into docker, on raw and dev environments would be work. I check it deeply.

**Comment by wlorenzetti** [comment]
It should be due to a PyQGIS bug: https://github.com/qgis/QGIS/issues/36977
