### ISSUE TITLE
Edit Geoconstraints

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-admin#113]
On this project
http://64.225.77.93:8080/en/map/editing-demo/qdjango/7/#

I set a geonconstraints for **viewer1** (**viewer1/G3wsuite123**) based on **Work Areas** layer (**id=1**)

Viewer1 can edit only feature that intersect **Area1 (id=1)**

IT SEEMS DOESN'T WORK

I CAN'T EDIT ANYWHERE

**Comment by wlorenzetti** [comment]
@leolami I found the problem. 
![Schermata da 2020-06-06 18-02-01](https://user-images.githubusercontent.com/196809/83948797-316f0280-a820-11ea-9ec7-c9f0f4f2ce9a.png)

User viewer1 is int the user group Viewer Group A, so I aspected to editing buondings into working area with id=1 and id=3, but is not work. 
If you try to delete rule for user group or for user viewer1 or 2 iit's work.

**Comment by wlorenzetti** [comment]
@leolami in fact as you can see in the follow code:
```python
            if rule_parts:
                expression = ' AND '.join(rule_parts)
                current_expression = qgis_feature_request.filterExpression()

                if current_expression:
                    expression = '( %s ) AND ( %s )' % (current_expression, expression)
```
expressions ad joined by `AND`.
