### ISSUE TITLE
Install G3WSuite on Ubuntu 18.04

### ISSUE THREAD

**Issue by dmiolo** [g3w-suite/g3w-admin#127]
I tried to install G3W Suite following the readme guide but at the installation point using `paver install` command, I get the error "ModuleNotFoundError: No module named 'qgis'"
QGIS is correctly installed on the machine.
How can I solve it?

Ubuntu 18.04

**Comment by wlorenzetti** [comment]
Hi @dmiolo, thanks for issue, in effect there 's a mistake on README.

To use QGIS API, you have to create your *virtualenv* with `--system-site-packages` option, so as its manual says: *give the virtual environment access to the system site-packages dir*.

**Comment by wlorenzetti** [comment]
Close for time passed.
