### ISSUE TITLE
Data not saved in persistent storage

### ISSUE THREAD

**Issue by nislamnreca** [g3w-suite/g3w-admin#133]
I have created instance with g3w-suite-docker.
After a restart, I see, data I saved in my previous session is not persistent.

**Comment by wlorenzetti** [comment]
Hi @nislamnreca, 
in your _.env_ file do you change `WEBGIS_DOCKER_SHARED_VOLUME` example value `/tmp/shared-volume-g3w-suite`?

Try to change it, and use a path not in `/tmp` folder.
In a linux SO _/tmp_ folder is temporary and it id cleaned every time you restart the machine.

**Comment by nislamnreca** [comment]
I have changed WEBGIS_DOCKER_SHARED_VOLUME value to /opt/shared-volume-g3w-suite in place of /tmp/shared-volume-g3w-suite. Data is now persistent after restart of the machine. The issue is resolved.

**Comment by nislamnreca** [comment]
I have changed WEBGIS_DOCKER_SHARED_VOLUME value to /opt/shared-volume-g3w-suite in place of /tmp/shared-volume-g3w-suite. Data is now persistent after restart of the machine. The issue is resolved.
