### ISSUE TITLE
Base layer from cached layer

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-admin#143]
It doesn't seem to work

Verifiable with the  base layer named **_Topograpich_** and added to this project 
https://dev.g3wsuite.it/en/map/g3w-suite-demo/qdjango/3/

The base layer was built starting from the CTR layer present on the same project

**Comment by leolami** [comment]
When creating the base layer it would be useful to be able to load the associated image and then visible when choosing the base layer

**Comment by wlorenzetti** [comment]
@leolami ok I find the bug. For image yes it's a programmed issue.

**Comment by leolami** [comment]
The problem is always present

You can chek it on https://dev.g3wsuite.it/en/map/g3w-suite-demo/qdjango/3/

Base layer: CTR
