### ISSUE TITLE
Layer visibility info

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-admin#144]
The CTR should light up below 2.501
If I turn it on and go below 2.501 it sees correctly, when I go back above 2.501 it turns off but on the TOC it remains checked and does not return gray.
I would expect it to turn gray with the visibility scale popup

**Comment by leolami** [comment]
https://dev.g3wsuite.it/it/map/g3w-suite-demo/qdjango/3/

**Comment by wlorenzetti** [comment]
@volterra79 @leolami this issue is still present?

**Comment by wlorenzetti** [comment]
@volterra79 @leolami ping...

**Comment by leolami** [comment]
The popup seems to be no longer visible...

@volterra79 can you check it here?

https://v31.g3wsuite.it/it/map/arpa-liguria/qdjango/29/
