### ISSUE TITLE
 'NoneType' object has no attribute 'isVisible'

### ISSUE THREAD

**Issue by lucamanga** [g3w-suite/g3w-admin#145]
Hello,
I have uploaded a qgis 3 project, but I have this error:

[Project error on layers()]-- [Layer error on isVisible(giuseppe20161121084434337)]-- 'NoneType' object has no attribute 'isVisible'

![immagine](https://user-images.githubusercontent.com/23235179/94409863-031e8580-0177-11eb-8ae2-27e491a47dff.png)

The 'giuseppe20161121084434337' is a Postgres layer

how can I fix this problem?

Thank you in advance

**Comment by wlorenzetti** [comment]
Hi @lucamanga , what branch of g3w-suite are you using? What's the qgis project version?

**Comment by lucamanga** [comment]
> Hi @lucamanga , what branch of g3w-suite are you using? What's the qgis project version?

In my docker-compose.yml:
```image: g3wsuite/g3w-suite-dev:latest```
Qgis project version: ```3.10.5```

**Comment by wlorenzetti** [comment]
Its very strange behavior, are you using branch v3.0.x  from g3w-suite-docker? Can you upload here your qgis test project cleared from uaer a password db?

**Comment by lucamanga** [comment]
I think I found the issue.
The project has entries that are referring from an old layer that is deleted from the TOC, but there are remains in the QGS project file.

**Comment by lucamanga** [comment]
I've deleted those old remainings and I can now upload the project.
