### ISSUE TITLE
Filtering options

### ISSUE THREAD

**Issue by nislamnreca** [g3w-suite/g3w-admin#147]
Hello,
I am new to g3w.
When I search in a layer by providing search criteria. I find the feature, but I cannot filter the dateset to make it smaller.
I am not sure if I am missing something.
Is there a way to filter the datasets of underlying layers?

**Comment by wlorenzetti** [comment]
Hi @nislamnreca sorry but I don't understand very well your question. Where do you do your search? On attributes table?

**Comment by nislamnreca** [comment]
Hi,
Yes, I search on the attribute table. When I search, I see the feature is highlighted on the map, but I  expected non-matching features would not be shown on the map.
Thanks

**Comment by leolami** [comment]
Attribute table filtered  by map contenent is now available on 3.2 versione
