### ISSUE TITLE
Content based legend?

### ISSUE THREAD

**Issue by lucamanga** [g3w-suite/g3w-admin#150]
Hello, it is possible to have a content based legend?
In the documentation of Qgis Server:

```
Context based legend. These parameters let the client request a legend showing only the symbols for the features falling into the requested area:
    BBOX the geographical area for which the legend should be built
    CRS / SRS the coordinate reference system adopted to define the BBOX coordinates
    WIDTH / HEIGHT if set these should match those defined for the GetMap request, to let QGIS Server scale symbols according to the map view image size.
Context based legend features are based on the UMN MapServer implementation
```

**Comment by wlorenzetti** [comment]
G3W-Client call once GetLegendGraphics at the start of the map  and recall the service if a layer into the toc is checcked/unchecked. 
I'm going to add this option like as ehnancement in a future release, activatable by a setting option.

**Comment by wlorenzetti** [comment]
It will be available with v3.1.
![Schermata da 2020-10-15 11-21-09](https://user-images.githubusercontent.com/196809/96104030-a17d4b80-0ed8-11eb-8710-18dd70c44013.png)

**Comment by lucamanga** [comment]
Excuse me, I could not find this option. See here. At bottom I have 3.1 version: 

     G3W-SUITE Versione 3.1.v.3.1.x-20201217100504: administration GIS application. 

![immagine](https://user-images.githubusercontent.com/23235179/103296786-20255780-49f7-11eb-8764-889decb6c1fd.png)

**Comment by wlorenzetti** [comment]
Sorry i forget to add it, I just push this fix https://github.com/g3w-suite/g3w-admin/commit/ec49d2a465d28a2767613d25bad3bb36ed0b4938.
Try to rebuild docker image...

**Comment by lucamanga** [comment]
> Sorry i forget to add it, I just push this fix [ec49d2a](https://github.com/g3w-suite/g3w-admin/commit/ec49d2a465d28a2767613d25bad3bb36ed0b4938).
> Try to rebuild docker image...

Thank you, but it seems not working: I clicked on "Context base legend" check, then on the "save" button, when I go back that check remains unchecked

**Comment by wlorenzetti** [comment]
Sorry @lucamanga , I'm bit tired. I restore the old situation without checkbox for context legend. (so please update your docker image).
You have to set this option on QGIS desktop project settings not on g3w-suite.
![Schermata da 2020-12-30 09-10-31](https://user-images.githubusercontent.com/196809/103338502-e9931f80-4a7e-11eb-90be-7f884bbbbd15.png)

**Comment by lucamanga** [comment]
OK! Thank you and ... sorry for the stressing :-)
