### ISSUE TITLE
Caching system seems not working

### ISSUE THREAD

**Issue by lucamanga** [g3w-suite/g3w-admin#151]
Hello,

I enabled the caching for a layer on a local volume (from docker image), see below.
The problem is that all these generated tiles are empty images. Is there any way to see log of TileCache to search errors eventually?
(if I turn off the caching for that layer, it works correctly)
```
tile_cache/
└── qdjango133
    ├── 2
    │   └── 000
    │       ├── 000
    │       │   └── 000
    │       │       ├── 000.png
    │       │       └── 001.png
    │       ├── 001
    │       │   └── 000
    │       │       ├── 000.png
    │       │       └── 001.png
    │       ├── 002
    │       │   └── 000
    │       │       ├── 000.png
    │       │       └── 001.png
    │       └── 003
    │           └── 000
    │               ├── 000.png
    │               └── 001.png
    ├── 4
    │   └── 000
    │       ├── 004
    │       │   └── 000
    │       │       ├── 000.png
    │       │       └── 001.png
    │       ├── 005
    │       │   └── 000
    │       │       ├── 000.png
    │       │       ├── 001.png
    │       │       ├── 002.png
    │       │       ├── 003.png
    │       │       └── 004.png
```

**Comment by wlorenzetti** [comment]
Layer chaching is a simple wrapping of TileStache, so when you set a cache of a layer you caching layer with your CRS. Your project has the same CRS layer?

**Comment by lucamanga** [comment]
Yes, see here:

**Project**
```
  <projectCrs>
    <spatialrefsys>
      [...]
      <srid>25832</srid>
      <authid>EPSG:25832</authid>
    </spatialrefsys>
  </projectCrs>
```

Layer (all layers have this CRS definition):
```
    <maplayer
        [...]
         <srid>25832</srid>
          <authid>EPSG:25832</authid>
        </spatialrefsys>
      </srs>
```

**Comment by lucamanga** [comment]
I have set the SRS to 25832 in the admin panel, in the group definition:
![image](https://user-images.githubusercontent.com/23235179/95979875-9bc23000-0e1c-11eb-9359-670900590cf3.png)

**Comment by wlorenzetti** [comment]
Ok l'm going to investigate.

**Comment by wlorenzetti** [comment]
@lucamanga could you upload a project with a small dataset?

**Comment by wlorenzetti** [comment]
@lucamanga with new version is it working?

**Comment by lucamanga** [comment]
OK. Now it's working. (Maybe when it was not while using subpath domain, a thing to test...)
