### ISSUE TITLE
Layer interface restructuring

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-admin#154]
**Proposal**
Change the order of the columns as follows:

- Alias  layer
-  Nome layer
- Tipo
- External WMS
- WFS
- Actions
- No legend
- Various download

**Bug**
The small popup indicating the number of active widgets for each type of tool appears visible only for searches and not for other tools.
Then it seems that the pop with the number of active searches has moved to the cache symbol ...

**Comment by leolami** [comment]
![immagine](https://user-images.githubusercontent.com/4012899/96885791-39ec7080-1483-11eb-877a-17cb6b3618d0.png)

**Comment by leolami** [comment]
The icons about editing, alphanumeric constraints and geo constraints must be near

**Comment by wlorenzetti** [comment]
@leolami I left action at the start of row, what do you think about?

**Comment by wlorenzetti** [comment]
like this?
![Schermata da 2020-11-04 16-37-56](https://user-images.githubusercontent.com/196809/98131991-2ea23780-1ebc-11eb-8f00-0f6a7ffcf20a.png)

**Comment by leolami** [comment]
Ok but but wms external after Type

**Comment by lucamanga** [comment]
Question: can I use the Identify button on these 'external wms' layers?

**Comment by wlorenzetti** [comment]
> Question: can I use the Identify button on these 'external wms' layers?

@lucamanga yes.

P.s.
If you're using G3W-SUITE for build a public service, please sent us the public url. It could be nice build a 'use case' page :).

**Comment by lucamanga** [comment]
@wlorenzetti actually it's an very early "alpha" stage, and it is still in intranet, for now.
We are stress-testing all its features, for now

**Comment by wlorenzetti** [comment]
> We are stress-testing all its features, for now

Thanks ;)
