### ISSUE TITLE
ACL for fields in layers

### ISSUE THREAD

**Issue by lucamanga** [g3w-suite/g3w-admin#155]
Hello,

is it technically possible to hide one or more fields of a layer, based on ACLs ?

i.e.

viewer1 --> can see two additional fields
viewer2 --> cannot see those fields

**Comment by wlorenzetti** [comment]
@leolami I don't remeber by this feature is not present into G3W-SUITE, right?

**Comment by leolami** [comment]
Hi @lucamanga 
This option is not yet implemented and it will not be even in the next version whose release is scheduled for next November 15th

This function will be implemented in version 3.2 scheduled to coincide with the release of the new QGIS LTR

**Comment by leolami** [comment]
Today it is possible to filter (in visualization and editing) the geometries of a layer on the basis of alphanumeric filters or using QGIS expressions

**Comment by lucamanga** [comment]
@leolami 
> Today it is possible to filter (in visualization and editing) the geometries of a layer on the basis of alphanumeric filters or using QGIS expressions

So, today I can hide a layer entirely, on ACL basis? For example for "role1" I can show the layer X, while it is hidden for "role2"?

**Comment by leolami** [comment]
Yes. For example you can put a constraints as **id IS NULL** to hide all the geometries of a layer

NB: the layer will always be present in the toc

**Comment by leolami** [comment]
See the paragraph **Alphanumeric / QGIS expressions Constraints** on the on line manual
https://g3w-suite.readthedocs.io/en/v.3.0.x/g3wsuite_editing.html#administration-settings

**Comment by lucamanga** [comment]
Thank you @leolami . Should I open a new bug ticket about hiding layers in TOC for certain users?

**Comment by leolami** [comment]
Of course.
But set it as an enhancement
