### ISSUE TITLE
WMS servicetype for BaseLayer 

### ISSUE THREAD

**Issue by lucamanga** [g3w-suite/g3w-admin#156]
Hello,

in the example on bug #40 I see the supported server types (WMST, Bing, TMS and OSM). Can I add a WMS based base layer?

**Comment by wlorenzetti** [comment]
@volterra79 is it possible?

**Comment by volterra79** [comment]
@lucamanga at moment is not possible. We add it to version 3.1.0

**Comment by lucamanga** [comment]
> @lucamanga at moment is not possible. We add it to version 3.1.0

@volterra79 please add an option to get "single tile" WMS, thank you!

**Comment by volterra79** [comment]
@lucamanga i add a an option
**single**: true/false
ok?

**Comment by lucamanga** [comment]
@volterra79  perfect! (singleTile would be better as an option name, but it's okay with your name)

**Comment by volterra79** [comment]
@lucamanga **singleTile** will be the option

**Comment by wlorenzetti** [comment]
@volterra79 this is added to current dev?

**Comment by volterra79** [comment]
yes

**Comment by billjwilliamson** [comment]
For testing, this example works OK for me in G3W-SUITE Version 3.1.dev-20201210111611

(target site would be Sydney Australia)
## NSW Six Road Layer

Name:: NSW Six Road
Title:: NSW Six Road
Icon:: six_base_thumbnail.png
Description:: Base road map from the NSW Govt Six Service
Property::
{
"crs":
{"epsg": 3857,
"proj4":"+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs",
"geographic":False,
"axisinverted":False
},
"url": "https://maps.six.nsw.gov.au/arcgis/rest/services/public/NSW_Base_Map/MapServer/tile/{z}/{y}/{x}",
"servertype": "TMS",
"attributions": "<a href='https://sdi.nsw.gov.au/catalog/search/resource/details.page?uuid=%7B7DF76070-8307-49A2-A381-3D9686EAFDDC%7D' target='_blank'>Imagery - NSW Govt</a>" " Creative Commons"
}

**Comment by Raruto** [comment]
@lucamanga it's ok for you, can we close this?
