### ISSUE TITLE
Virtual layer (join based filter) error

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-admin#157]
I created a project based on SpatiaLite with two layers:

- airports (points)

- airports_info (alphanumeric)

I created a join 1:1 between this two layers
I created a filter based on attribute of the joined table (airports_info)
QGIS create a virtual layer with the result of the filter

When I upload the porject I have a 500 server error

I attach DB Spatialite (3857) and QGIS project

[virtual.zip](https://github.com/g3w-suite/g3w-admin/files/5493283/virtual.zip)

**Comment by wlorenzetti** [comment]
It was a QGIS-server bug, fixed by @elpaso https://github.com/qgis/QGIS/pull/39819.
