### ISSUE TITLE
[enhancement] Custom authorization back-end for g3wsuite-admin or -client?

### ISSUE THREAD

**Issue by lucamanga** [g3w-suite/g3w-admin#159]
Hello,

in our organization we have Active Directory.
It would be useful to have ACL roles linked to a group of users in Active Directory.
Of course, we should enable kerberos authentication on ngnix side.
Have you made some test about this?

**Comment by wlorenzetti** [comment]
@lucamanga we have a private django module to do that. `g3w-admin-authladap` can login against AD/Ldap server..

**Comment by lucamanga** [comment]
@wlorenzetti perfect, so this is already implemented. Thank you
