### ISSUE TITLE
Basemap is not visible 

### ISSUE THREAD

**Issue by teepie** [g3w-suite/g3w-admin#168]
Please check these two URLs 
demo.asemakaava.fi/en/map/nakkilan-kunta/qdjango/11/

demo.asemakaava.fi/en/map/test_3857/qdjango/3/

In  the first one can't see the Basemap (OSM) even if it selected
The second one works ok.

The main difference between the projects is that the first one is on EPSG:3876 and the second one on EPSG3857.

**Comment by wlorenzetti** [comment]
@volterra79 can you check it?

**Comment by volterra79** [comment]
fixed
