### ISSUE TITLE
Problem with adding new basemap

### ISSUE THREAD

**Issue by teepie** [g3w-suite/g3w-admin#169]
Hi
I tried to add a new basemap:
Basemap definition looks like this:
{
 "crs":
{"epsg": 3067,
"proj4": "+proj=utm +zone=35 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs", 
"geographic": False, 
"axisinverted": True
},
"url": "https://tiles.kartat.kapsi.fi/peruskartta_3067/{z}/{x}/{y}.jpg",
"servertype": "TMS",
"attributions": "TESTI123"
}

Basemap is selectable in the Client app(MML Kii) , but it doesn't appear on the map even though selected
[demo.asemakaava.fi/en/map/test_3857/qdjango/3/](url)

![addedbasemapnotvisible](https://user-images.githubusercontent.com/8089255/101662241-edb8b800-3a51-11eb-81db-1bda51f174dc.png)

**Comment by wlorenzetti** [comment]
Hi @teepie, is possible TMS service is in 3857 intead of 3067? QGIS desktop open it in 3857...

**Comment by wlorenzetti** [comment]
Hi again @teepie sorry I reply to fast, we are looking for the issue.

**Comment by wlorenzetti** [comment]
@volterra79 this issue is related to issue #168?

**Comment by billjwilliamson** [comment]
Maybe try this as a test


Name:: Google Hybrid
Title:: Google Hybrid Basemap
Icon:: gmaps_icon.png
Description:: Google Hybrid Basemap
Property::
{
   "crs":{
      "epsg":3857,
      "proj4":"+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs",
      "geographic":False,
      "axisinverted":False
   },
   "scalebasedvisibility":False,
     "url":"https://mt1.google.com/vt/lyrs=y&x={x}&y={y}&z={z}",
   "servertype":"TMS",
   "attribution": "<a href='https://www.google.com/intl/en_au/help/terms_maps/'>Copyright Google and Maxar</a>"
}
