### ISSUE TITLE
Zoom to layer doen't work

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-admin#170]
Zoom to layer function does not work

You can test it here:

https://v31.g3wsuite.it/it/map/arpa-liguria/qdjango/29/

Report the correction on dev release too

Thanks

**Comment by wlorenzetti** [comment]
@volterra79 the project has layer with epsg diffrent from map one, so also bbok into layer config property is in the layer native epsg. Is possibile to you reproject or I had to add bbk in epsg map system?
