### ISSUE TITLE
Layer transparency

### ISSUE THREAD

**Issue by valtterilap** [g3w-suite/g3w-admin#176]
Hi,

Is it possible to change layer transparency from the web app? I know if you save the layer transparency in Qgis, it is shown in the web app. Could it be possible to change the opacity on the fly directly from the web app?

**Comment by wlorenzetti** [comment]
Hi @valtterilap at the moment is not possible. This feature  could be add to the next releases.

**Comment by valtterilap** [comment]
Thank you for the fast response. We would be really interested having this feature.

**Comment by Raruto** [comment]
It's been a while here...

BTW it will most likely be included in the next stable release (**g3w-admin@v3.6**)

For more information: https://github.com/g3w-suite/g3w-client/pull/354

👋 Raruto
