### ISSUE TITLE
Minor client bugs

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-admin#177]
https://dev.g3wsuite.it/en/map/g3w-suite-demo/qdjango/31/

**1. Query function** 
It would be better that after opening the right panel (search results, generic plots, plots in the query form ...) the query icon would always remain active
Now if after the query I open the plots inside the form or if I open the graphs directly from the Charts menu, the query function is disabled

**2. Download icons**
Put a single download icon with the possibility to choose, via the drop-down menu, the format to download

**3. Link to relations**
I would remove the phrase "Click to show relations [relation name]" from the links in the query form and leave only the icon and name of the relation.

**4. Right edge of the relationed attribute table**
After opening the chart related to related data, is it possible to create a border of the table on the right as on the left?

![immagine](https://user-images.githubusercontent.com/4012899/102869397-d6a79c00-443b-11eb-922e-69c2384bd182.png)

**5. Number of records listed in the attributed tables**
It would be useful if one chooses to display (for example) 50 records at a time for the table of a layer, this would be remembered when the table is closed and reopened

**6 Plots on related childs**
If you access to relation form from general icon relation you can see the plots icon in the relation tables.
If you query the "Builder" layer and access to relation from query form (links in the Relations tab), you can't see the plots icon

**7 Editing form dimension**
It would be useful to remember the size set by the user in an editing session, so that when the following feature is edited, the form reopens at the same size

**8 Main title and axis title with more of one plots**
When you show 2 or more plots main and axis titles disappear

**Comment by wlorenzetti** [comment]
@volterra79 are you working on this issue?

**Comment by wlorenzetti** [comment]
@volterra79 can be it closed?

**Comment by leolami** [comment]
Only this request have to be fix:

**2. Download icons**
Put a single download icon with the possibility to choose, via the drop-down menu, the format to download
