### ISSUE TITLE
WMS URL not working

### ISSUE THREAD

**Issue by teepie** [g3w-suite/g3w-admin#178]
![wmslayerQgis](https://user-images.githubusercontent.com/8089255/103282202-b51b5700-49dd-11eb-90ec-aa2a14beaf9a.png)

HI
Please see the attached screenshot.
Looks like that a WMS service has a problem:
It replies to getCapabilities request, but doesn't return the layers itself

**Comment by wlorenzetti** [comment]
Hi, I just try and looking on qgis desktop. I found the problems.
Looiing con qgis calls to server I see that your original deploy is on port 8080 instead on port 80. i suppose you are using a reverse proxy to redirect call on port 80 to 8080.
The solutions are 2:

1. No remove reverse proxy: in this case you can use it on QGIS desktop checking options _Ingore GetMap/GetTile URI..._ and _Ingnore GetFeatureInfo ..._
2. Remove reverse proxy: un install your reverse proxy server and running your docker dploy on port 80, into `docker-compose.yml` change __nginx__ settings:

```yaml
 ports:
      - "8080:8080"
      - "443:443"
```
to


```yaml
 ports:
      - "80:8080"
      - "443:443"
```

**Comment by teepie** [comment]
Hi, 
Thx for reply.

**About solution 1:** is not feasible and it is actually not fully working - I get the map, but still get the "Connection refused"

![wmslayer_2](https://user-images.githubusercontent.com/8089255/103530857-de7e2c00-4e90-11eb-8647-ad1800bd23dd.png)


**Solution 2:** we already do have setting:

```yml
ports:
  - "80:8080"
  - "443:443"
```

in yml file
?

Please advise

**Comment by wlorenzetti** [comment]
Hi @teepie with new version have you problems?

**Comment by Raruto** [comment]
I'm closing here due to inactivity, feel free to open a new pull request with additional details if you're still experiencing some troubles.

👋 Raruto
