### ISSUE TITLE
Question related to HTTPS setup on dockerization

### ISSUE THREAD

**Issue by teepie** [g3w-suite/g3w-admin#179]
Question related to HTTPS setup on docker version
Is the documentation 
https://g3w-suite.readthedocs.io/en/latest/docker.html
Up to date for version 3.1.
We have tried to follow the instructions (and tried a lot of other experimental things :)).
Without success:
Error message from startup
"nginx exited with code 1"

I can&will provide more information once you have verified the documentation

**Comment by tudorbarascu** [comment]
The documentation works. At leat it worked for me. All the best.
