### ISSUE TITLE
SVG folder?

### ISSUE THREAD

**Issue by luca76** [g3w-suite/g3w-admin#180]
Hello,

I've created, with File Manager, a **svg** (written in lowercase) folder, with another sub-folders and SVGs into it.
The proejct I uploaded have all symbols with relative paths.
But I cannot view them, they are all replaced with the "?" mark.

Am I missing something?

**Comment by luca76** [comment]
This is my folder structure

![image](https://user-images.githubusercontent.com/5095918/103289389-5955cb80-49e7-11eb-93ec-85f177b7905a.png)

**Comment by wlorenzetti** [comment]
Ok the problem I think is due to QGIS3.ini file missing.

I'll do a fix on dev and v3.1.x branch soon.

**Comment by luca76** [comment]
thank you in advance!

**Comment by wlorenzetti** [comment]
I just push this commit https://github.com/g3w-suite/g3w-suite-docker/commit/6aa2348a4658b23f8e7d971407d1cbd6400f64ce, it could be fix the issue.
Update the docker scripts code and `docker-compose up d` again.

**Comment by luca76** [comment]
excellent! Now it works.
