### ISSUE TITLE
Issue with prints in 3.1

### ISSUE THREAD

**Issue by valtterilap** [g3w-suite/g3w-admin#185]
Hi,

When creating a print using 3.0 works fine but when creating a print with 3.1 it only shows one layer.

![3 0 print](https://user-images.githubusercontent.com/64913858/103407029-a5c71580-4b65-11eb-83db-c9ff083a046b.png)
Print using 3.0

![3 1 print](https://user-images.githubusercontent.com/64913858/103407038-af507d80-4b65-11eb-86af-3470e7baa8fd.png)
Print using 3.1

Both prints are using the same project file and layout.

However, neither of the prints does support the SVG logo we have. Below is the same layout opened in Qgis.
![qgis print](https://user-images.githubusercontent.com/64913858/103407107-f8083680-4b65-11eb-9bff-e4715fa15cf6.png)

**Comment by wlorenzetti** [comment]
Hi, Is layer visibility scale dependent?
For svg, update your g3w-suite-docker v3.1.x branch, in the past days I just add SVG management, after update you have to create a folder named 'svg' inside your filemanager space and upload there your svg.

**Comment by valtterilap** [comment]
Visibility is scale dependent but both of the prints are using same scale and same project file

**Comment by wlorenzetti** [comment]
ok but the scale of above print images are ate the same scale value of visibility layer limit?

**Comment by leolami** [comment]
Hi Valtteri
is this webgis with free access?
Can you send us the URL, so we can check

Thank you

**Comment by valtterilap** [comment]
Hi,
Here is the link for 3.0 version http://devg3.asemakaava.fi/en/map/nakkila-3067/qdjango/23/
And for 3.1 http://kaavao.asemakaava.fi/en/map/nakkilan-kunta/qdjango/3/#

**Comment by volterra79** [comment]
@valtterilap we fixed the issue. Please pull the v3.1.x and let you know. Thanks

**Comment by leolami** [comment]
About the logo in the print layout

Have you load the logo on the project_data direcory?

https://g3w-suite.readthedocs.io/en/v.3.1.x/projectsettings.html#print-layouts

**Comment by valtterilap** [comment]
Everything including the SVG logo works fine now!
