### ISSUE TITLE
Editing tools management

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-admin#186]
On a project I define the editing permissions for layer A (user viewer1) and for user B (user viewer2).

When I access the project with (for example) user A and access the editing, I find the editing tools available for both layer A and layer B

If I try to activate editing on layer B it gives me an error but if I insist it makes me edit even if (rightly) I don't save.

It should be avoided that the user who does not have editing permissions on a layer finds the editing tools in the list

**To be fixed on both 3.1 and DEV**

**Comment by wlorenzetti** [comment]
Fixed on commit, https://github.com/g3w-suite/g3w-admin/commit/d4b7d6a99ca3d397a4eeddd00b7641513950c0d0.
@leolami try again and close this issue.

**Comment by leolami** [comment]
It's ok on DEV

Can you fix also in 3.1?
