### ISSUE TITLE
Multiple editing on attributes

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-admin#189]
We need to add a new tool (there is also the icon on QGIS) to simultaneously edit the attributes of a set of selected geometries

The modification must only take place for the attributes defined on a generic form

The other attributes will keep the previous value for each feature

![immagine](https://user-images.githubusercontent.com/4012899/104190947-20711a00-541d-11eb-8046-a12bd1c0e7c0.png)

**Comment by leolami** [comment]
Promeoria:

- gestire la selezione multipla (non solo con bounding box)
- verifcare errore su allegati

Per il resto sembra funzione tutto bene!

**Comment by volterra79** [comment]
fixed in dev
