### ISSUE TITLE
Metadata of single layer

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-admin#194]
The ABSTARCT field of the metadata layers only reports the first letter of the content defined in QGIS

![immagine](https://user-images.githubusercontent.com/4012899/104742402-ab6a5100-574a-11eb-9c11-c4051c64f964.png)

![immagine](https://user-images.githubusercontent.com/4012899/104742705-1025ab80-574b-11eb-947d-8edc60e7d7eb.png)

The same on DEV

**Comment by wlorenzetti** [comment]
@volterra79 I just verified the correct sent to the client by admin of abstract value.
![Schermata da 2021-01-18 16-20-16](https://user-images.githubusercontent.com/196809/104933416-2d57b580-59a9-11eb-80e8-0b0d84af753e.png)

**Comment by volterra79** [comment]
fixed in dev
