### ISSUE TITLE
Map attribution

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-admin#195]
In a old version (see here: http://webgis.simfvg.it/it/map/consultazione-prgc-uti-carnia/qdjango/17/) it was possible set the copyright of the map

![immagine](https://user-images.githubusercontent.com/4012899/104743370-ea4cd680-574b-11eb-981f-aea385b8fe55.png)

It was possible set this copyrigth in the GROUP form

![immagine](https://user-images.githubusercontent.com/4012899/104743598-2a13be00-574c-11eb-800d-310a92b0c4d6.png)

Now it does'nt work (3.1 and DEV)

**Comment by billjwilliamson** [comment]
Hi @leolami I found that base layers worked quite differently now with 3.1. Have a look at this ticket, it should reveal how attributions work. https://github.com/g3w-suite/g3w-admin/issues/156

**Comment by wlorenzetti** [comment]
@volterra79 I check on `initconfig` admin api and inside `group` if you set `header_terms_of_use_text` ad `header_terms_of_use_link` you can find them.

**Comment by wlorenzetti** [comment]
@leolami it ca be closed.
