### ISSUE TITLE
How to disable "open attribute table" in client?

### ISSUE THREAD

**Issue by lucamanga** [g3w-suite/g3w-admin#197]
Hello,

it is possible to disable the "open attributes table" sub-menu, by right clicking on the layer in the TOC?

**Comment by volterra79** [comment]
@lucamanga at the moment is not possible. We have to think about an option  in admin.

**Comment by wlorenzetti** [comment]
@volterra79 now on config API layer object you find `not_show_attributes_table`. Please write  here when you implemented it.

**Comment by volterra79** [comment]
@wlorenzetti added in dev branch

**Comment by lucamanga** [comment]
I don't understand if this allows to disable for some or to all layers
