### ISSUE TITLE
Path on the downloaded QGIS projects

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-admin#199]
When I download a QGIS project from Admin I find this kind of paths:

Es. for Geopackage
**/shared-volume/project_data/geopackage/building_management.gpkg|layername=buildings**

If i try to open this project i have an error because the rigth path should be:

**../project_data/geopackage/building_management.gpkg|layername=buildings**

as in the original uploaded project

**Comment by wlorenzetti** [comment]
A the moment is not possible.
