### ISSUE TITLE
Minor enanchment

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-admin#201]
reduce the size of the session dedicated to Gis3W in the credits
![immagine](https://user-images.githubusercontent.com/4012899/106114720-2d497980-6150-11eb-980c-384fe5be11c8.png)

Add to the message relating to the failure to load a WMS the sentence: "Try to reload the map"

Change the print message:
**"The layers shown in the print could be those defined on the QGIS project (through the management of themes) and not those displayed on the map"**
with
**"The layers shown in the print could be those defined on the project and not those displayed on the map"**

**Comment by leolami** [comment]
Ok for the resolution

In order to simplify the workflow I make these two proposals:

- Make the function of the "Map filter" icon more understandable immediately

![immagine](https://user-images.githubusercontent.com/4012899/106266741-19be1180-6229-11eb-829d-3a8843be9d68.png)


- Add the filter tool (always synchronized) at the level of the various graphs but we need to think about this better

**Comment by wlorenzetti** [comment]
Can be it closed?
