### ISSUE TITLE
Streetview not working properly

### ISSUE THREAD

**Issue by valtterilap** [g3w-suite/g3w-admin#204]
Streetview is not working correctly but showing a watermark "For development purposes only," and colors are negative. Is there a way to fix this? I included a screenshot below.
![image](https://user-images.githubusercontent.com/64913858/107388204-406c2a00-6afe-11eb-969d-b8f7e2a8712b.png)

**Comment by wlorenzetti** [comment]
Hi @valtterilap G3W-SUITE uses Gis3W Googgle API Key, you've to use a your Google API key and set into `settings_docker.py' in this way:
```python
....
VENDOR_KEYS = {
     'google': '<your_api_key>',
     'bing': '<your_api_key>'
}
...
```
Don't forget to update your g3wsuite/g3w-suite:v3.1.x image..

**Comment by valtterilap** [comment]
Thanks, works fine now.
