### ISSUE TITLE
Values order in search

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-admin#206]
The values ​​shown in the drop-down menu should be arranged in alphabetical order

![immagine](https://user-images.githubusercontent.com/4012899/108478689-1a305200-7295-11eb-9196-ca22dea7c0ee.png)

**To fix also in 3.1**

**Comment by wlorenzetti** [comment]
Fix for dev with https://github.com/g3w-suite/g3w-admin/commit/d8901a74c416b198ad2611e732e234d36284c021
Fix for v.3.1.x with https://github.com/g3w-suite/g3w-admin/commit/41f82b00552f98b1fa6aa217bde25c674476413a
