### ISSUE TITLE
Separate editing and viewing functions at the constraint level

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-admin#207]
Geographical and alphanumeric constraints (SQL or QGIS expression) should be able to specify whether these constraints hold for:
- visualization
- edititing
- both of them

The default option should be visualization
I would use a chckbox system for the choiche

**Comment by wlorenzetti** [comment]
@leolami where do you want the options:
At level of main contraint:
![Schermata da 2021-03-10 08-24-13](https://user-images.githubusercontent.com/196809/110592147-362f6100-817a-11eb-91da-a4b8a1c51718.png)
or at level of single rule?
![Schermata da 2021-03-10 08-24-26](https://user-images.githubusercontent.com/196809/110592181-40515f80-817a-11eb-8312-2d583b6dcf56.png)

**Comment by leolami** [comment]
I would like this option at the level of the generic definition of the constraint

In this way you will be able to filter more easily, at the single rule / user level, the viewer users from the viewer and editor users

**Comment by leolami** [comment]
**Alphanumeric constraints**

When defining the constraints (when I name it and define view / editing option) it returns: ERROR 400

**Comment by leolami** [comment]
Only if I choose **Active for visualization** option 
Only this single option

**Active for edit** and 	**Active for visualization and editing** options work.

**Comment by dotsLand** [comment]
Hi 
Is it possible to pass the Userid or any other attribute if the user or usergroup is specified in SQL rule constraint?

![image](https://user-images.githubusercontent.com/107835719/235158394-bf3ab9a0-1c89-44be-aaba-9bd920e904ee.png)
