### ISSUE TITLE
Hide a layer for specific user or for Anonymususer

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-admin#208]
It would be interesting to be able not to display a specific layer for a specific user or for the anonymous user

The layer should disappear from the map and the TOC

**Comment by wlorenzetti** [comment]
Only viewers and viewer user groups.

**Comment by leolami** [comment]
But was the Anonymus user  also managed?

I try on DEV and it doesn't seem possible?

**Comment by leolami** [comment]
Can you change the color icon when the hide layer fucntion is active?

I try to hide two layer (buildings and work areas) for the Viewer1 and it works

Then I remove this settings (re-adding Viewer1 to the list of the viewer tha can see this layers) but Viewer1 can see this layer anymore in the map

https://dev.g3wsuite.it/en/map/g3w-suite-demo/qdjango/97/

**Comment by wlorenzetti** [comment]
@leolami now it could be work.
