### ISSUE TITLE
Error on users created directly by Django admin panel

### ISSUE THREAD

**Issue by elpaso** [g3w-suite/g3w-admin#21]
The user created lacks `userbackend` and the whole user management in the application is unusable (error 500).

**Comment by wlorenzetti** [comment]
Why use Django admin panel?
'/users/add/' G3W-SUITE is the right place.

**Comment by elpaso** [comment]
Sure: I wouldn't recommend using the Django admin directly either.

But this is a (rather severe) bug anyway: a link to the Django admin panel is provided to users from the g3w admin panel and unless you remove the user management from the Django admin the error is still possible.

There is currently no way to recover a functional user management without manually adding the missing rows in the related table.

**Comment by elpaso** [comment]
@wlorenzetti thank you for the quick fix, I'll test it ASAP!

**Comment by wlorenzetti** [comment]
No wait, error persist..

**Comment by wlorenzetti** [comment]
@elpaso I don't known why, but now to add a userbackend to a user with a admin.StackedInline in Django admin form, you have to set also a description for userbackend section. I'm not sure but I think is as Django bug. 
Try and send me a feedback thanks!

**Comment by elpaso** [comment]
I tested the patch, it does not solve the issue.

**Comment by elpaso** [comment]
The commit above fixes the issue for me.

**Comment by wlorenzetti** [comment]
Thanks @elpaso!

**Comment by kaloyan13** [comment]
I get the same error using dev and 3.3.x branch.
It happens, when you try to create a user. The user is added, but when you try to list the users, it dies again, with same error.

[userbackend_error.txt](https://github.com/g3w-suite/g3w-admin/files/8089071/userbackend_error.txt)
[userbackend_stacktrace.txt](https://github.com/g3w-suite/g3w-admin/files/8089072/userbackend_stacktrace.txt)

**Comment by DavidGhedini** [comment]
I get the same error using the Front End (as well as Django panel).

**Comment by wlorenzetti** [comment]
Hi guys did you try to create user with admin user or with Editor Level 1 user?

**Comment by kaloyan13** [comment]
I tried to create non-admin user. Then I tried to create admin user, with viewer level/group (don't remember clearly). I also tried admin with Editor level.

At the end edited [g3w-admin/g3w-admin/usersmanage/utils.py](https://github.com/g3w-suite/g3w-admin/blob/25d55325ccf696a6ff162650ae32b7bea55a1cc9/g3w-admin/usersmanage/utils.py#L260) like this:
```
- if not obj.is_superuser and obj.userbackend.backend.lower() != USER_BACKEND_DEFAULT:
+ if hasattr(obj, 'userbackend') and not obj.is_superuser and obj.userbackend.backend.lower() != USER_BACKEND_DEFAULT:
```

**Comment by wlorenzetti** [comment]
@kaloyan13 I did some tests but nothing errors and django tests pass!. 
When you try to create a user as admin level 1 on user form can you see this select at the bottom of the form?

![Schermata da 2022-02-22 15-25-01](https://user-images.githubusercontent.com/196809/155152072-ac5e5acd-33ef-457b-9ddd-1928151a59a9.png)
