### ISSUE TITLE
Malfunction on display filters

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-admin#210]
On a layer (e.g. buildings) of a WebGis service I created an alphanumeric filter for a user (e.g. viewer1)

If you log in to the WebGis service as an anonymous user, NO LAYER is displayed

If I remove the filter for viewer1 everything works fine

[https://dev.g3wsuite.it/it/map/g3w-suite-demo/qdjango/34/](https://dev.g3wsuite.it/it/map/g3w-suite-demo/qdjango/34/)

**BACKPORT ON 3.1**

**Comment by wlorenzetti** [comment]
@leolami I just try on my local development installation and it works fine. I'm on QGIS server 3.16.4 and a project with shape.
Try with a PostGIS or Shape layer instead of GeoPackage.

**Comment by leolami** [comment]
I make a test with SHP file and I have the same results

https://dev.g3wsuite.it/it/map/test-deploy/qdjango/1/

It is sufficient to create an alphanumeric constraint (without even creating any rules). 
Anonymus user no longer sees any layers

Today I try to test it on PostGis

**Comment by leolami** [comment]
Same behavior with SpatiaLite data

Try to log into this project as an anonymous user

https://dev.g3wsuite.it/en/map/g3w-suite-demo/qdjango/82/

**Comment by wlorenzetti** [comment]
@leolami it could be fixed with commit https://github.com/g3w-suite/g3w-admin/commit/042c7ca1bae579c0672abb3b18e70d5aec929f75.
Check again...

**Comment by leolami** [comment]
It will be useful can set view constraints for Anonymus User
