### ISSUE TITLE
Logo and title on the header of the client

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-admin#211]
It would be advisable to add the same logo and header title management system present at the macro-group level, at the cartographic group level

![immagine](https://user-images.githubusercontent.com/4012899/109279326-e9629680-7819-11eb-8f17-b5052aede23c.png)

If the option is activated on both the macro-group and the group, the group wins

**Comment by wlorenzetti** [comment]
@leolami done, into 'logo' section of group form:
![Schermata da 2021-03-09 17-23-19](https://user-images.githubusercontent.com/196809/110503295-53254f00-80fc-11eb-99ce-a855673b8d61.png)
