### ISSUE TITLE
Order of the TOC menus: HIGH PRIORITY

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-admin#214]
We have two possibilities, we choose the simplest one:

SOLUTION A
At the project level it should be possible to define the order in which the three menus are arranged (Layers, Base, Legend)

At start-up, the one defined as first must always be visible

SOLUTION B
The order of the menus remains the current but at the project level it is defined which menu must be visible at start-up.

**Comment by wlorenzetti** [comment]
Add a form select into project main form:
![Schermata da 2021-03-08 12-02-39](https://user-images.githubusercontent.com/196809/110313190-60f8a880-8006-11eb-8ec4-05c14b81fb0e.png)

**Comment by wlorenzetti** [comment]
@leolami add into documentation.
