### ISSUE TITLE
Search on SHP

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-admin#215]
[https://dev.g3wsuite.it/it/map/test-32632/qdjango/43/](https://dev.g3wsuite.it/it/map/test-32632/qdjango/43/)

In this project there are three research based on SHP

- If the search is defined with **SelectBox**, no value appears in the drop-down menu

- If the search is defined with **AutoComplete**, the autocomplete shows correct values ​​but then the result is empty

- If the search is defined with **InputBox**, the result is empty even if you enter correct values

**BACKPORT ON 3.1**

**Comment by volterra79** [comment]
@wlorenzetti 
from client point of view is seems have no problem:

-  **If the search is defined with SelectBox, no value appears in the drop-down menu** (values of inputs are empty)
- **If the search is defined with AutoComplete, the autocomplete shows correct values ​​but then the result is empty** (request is corrent but server response with no results)
- **If the search is defined with InputBox, the result is empty even if you enter correct values** same issue above point

**Comment by leolami** [comment]
I tried to import the shp in PostGis and even in this case the searches don't work ....

I chek also teh presence of invalid geometries but they are all valid

Very strange

**Comment by leolami** [comment]
If i import the layer on PostGis and I try to create a search, it works

If i re-export the Postgis data in Shp and I try to create search on the new shp, it DOES'NT work

The search on the same SHP layer made on LizMap Work correctly
http://qgis.arpal.liguria.it/lm313/index.php/view/map/?repository=baora&project=balneazione

The search tool is on the rigth top
Pay attention beacuse you have to scroll down to see the Administration name

Here the SHP
[comuni_error.zip](https://github.com/g3w-suite/g3w-admin/files/6115370/comuni_error.zip)

**Comment by leolami** [comment]
Fixed with several topological corrections on the SHP
