### ISSUE TITLE
Login Portal Improvements / Bugs

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-admin#217]
**1. The logo displayed at the top left is too small, it should be increased**

![immagine](https://user-images.githubusercontent.com/4012899/109287085-6c3c1f00-7823-11eb-942f-a28de63f15a9.png)

![immagine](https://user-images.githubusercontent.com/4012899/109287293-adccca00-7823-11eb-84ce-db8038d11ac0.png)

**2. In the list of maps of the various groups, the overview map of the group is also incorrectly reported**

**Comment by wlorenzetti** [comment]
@volterra79 can you change css .logo class into .vue files and recompile it? Set max-width and max-height to 85%? (Try some voalues)
to change:

`g3w-admin/portal/frontend/src/components/default/Header.vue`
```js
            .img_container {

                .logo {
                    max-height: 70%;
                    max-width: 70%;
                }
            }
        }
```
