### ISSUE TITLE
AutoZoom on the features search results

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-admin#218]
It would be advisable to be able to define, at project level, the behavior linked to the results of a search.

Automatic zoom to the features of the results or not

**Comment by billjwilliamson** [comment]
Hello @leolami I think you are looking for https://g3w-suite.readthedocs.io/en/v.3.1.x/projectsettings.html#capabilities-wms-general-aspects "feature response"

**Comment by leolami** [comment]
Also for Anonymus user

**Comment by wlorenzetti** [comment]
@leolami add into documentation.

**Comment by wlorenzetti** [comment]
@volterra79 add `autozoom_query` property to project config api. https://github.com/g3w-suite/g3w-admin/commit/22595c5ef277487e9ea5e791234d71e90c0f5427

**Comment by wlorenzetti** [comment]
@volterra79 add here commit reference of client implementation, thanks.

**Comment by volterra79** [comment]
@wlorenzetti  https://github.com/g3w-suite/g3w-admin/commit/b2a78c48da85a485f599603dddbb78ee12879106

**Comment by leolami** [comment]
As agreed with @volterra79 , I have to check if it is necessary to add the autozoom also for the query results (in case of only one layer in the answer)
