### ISSUE TITLE
Direct log from the client

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-admin#224]
It would be useful to be able to log in directly at the level of the single webgis

Via a menu on the client header

It would be useful for free services but on which a specific user has special permissions (e.g. editing)

**Comment by wlorenzetti** [comment]
@leolami I didn't understand.. can you post a schema?

**Comment by leolami** [comment]
Free webgis
![immagine](https://user-images.githubusercontent.com/4012899/111028215-91b95300-83f5-11eb-9f9c-6beb35d84f3d.png)

Free webgis with **Log in** option
![immagine](https://user-images.githubusercontent.com/4012899/111028245-ba414d00-83f5-11eb-823a-198e2033a425.png)

The overlay log panel should open
![immagine](https://user-images.githubusercontent.com/4012899/111028283-f83e7100-83f5-11eb-9f93-1f81a76de8c9.png)

And the map refresh

**Comment by wlorenzetti** [comment]
@volterra79 add login_url to initConfig API, commit https://github.com/g3w-suite/g3w-admin/commit/38b0839a1d2aa89945f2bcf0d0f9ff0fc1135f8b
