### ISSUE TITLE
Plots: error on selection filter

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-admin#225]
https://dev.g3wsuite.it/en/map/g3w-suite-demo/qdjango/82/

Make a search (es. Type= Administrative Year = ALL)
Select the feature results
Active selection filter
See the plots

All the plots are empity

**Comment by wlorenzetti** [comment]
@leolami  I can see the plots:
![Schermata da 2021-03-13 11-38-13](https://user-images.githubusercontent.com/196809/111027439-a7784980-83f0-11eb-9892-3fa49231336b.png)

**Comment by wlorenzetti** [comment]
![Schermata da 2021-03-13 11-44-41](https://user-images.githubusercontent.com/196809/111027603-88c68280-83f1-11eb-9779-7c6ec2856993.png)

**Comment by leolami** [comment]
I test more
Before it didn't work...

**Comment by leolami** [comment]
Access to this project as **AnonymusUser**

https://dev.g3wsuite.it/en/map/g3w-suite-demo/qdjango/82/

Run a search (es. Type= Administrative Year = ALL)
Select the feature results
Active selection filter

The filter doesn't work (map and plots)

**Comment by wlorenzetti** [comment]
@leolami try now
