### ISSUE TITLE
Minor error on layer list

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-admin#228]
There is a problem in the style icon visualization

![immagine](https://user-images.githubusercontent.com/4012899/111183623-6333a780-85b0-11eb-96c2-8a352684c579.png)

Can you reorder in this way?

- cache
- edit
- geo constraints
- alpha constraints
- search
- style

**Comment by wlorenzetti** [comment]
@leolami check it now.

**Comment by leolami** [comment]
Can you reorder in this way?

    cache
    edit
    geo constraints
    alpha constraints
    search
    style

**Comment by wlorenzetti** [comment]
No
