### ISSUE TITLE
GPK download icon in the query results

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-admin#239]
Add a GPK download icon when it is active in administration setting

![immagine](https://user-images.githubusercontent.com/4012899/111866376-57a7fe00-896d-11eb-87c8-16dca7d365c2.png)

**Comment by leolami** [comment]
Also in the right click menù of the layer

![immagine](https://user-images.githubusercontent.com/4012899/111866859-b15df780-8970-11eb-9827-bb4580a09efc.png)

**Comment by leolami** [comment]
@volterra79 can you fix?

**Comment by volterra79** [comment]
@leolami fixed
