### ISSUE TITLE
Webgis title shown in the frontend

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-admin#256]
The title shown on the portal (frontend) does not correspond to those defined as Public title (Italian and English)

Instead, the title associated with the QGIS project is always shown

**Comment by wlorenzetti** [comment]
@leolami check on dev.g3wsuite.it it'd be fixed.

**Comment by wlorenzetti** [comment]
sorry I didn't push commits, next dev.g3wsuite.it update

**Comment by leolami** [comment]
On dev there isn't the frontend 

I cannot test on dev.....
