### ISSUE TITLE
Selection error

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-admin#257]
https://v32.g3wsuite.it/it/map/g3w-suite-demo/qdjango/106/

Try to:

- query a province in the map (es. FI)
- select the queried province
- switch on the selection filter
- query another province (es. AR)

The new province has the selection check active but it isn't select on the map

![immagine](https://user-images.githubusercontent.com/4012899/120324843-5c7f1b80-c2e7-11eb-9ce4-3b5771214d51.png)

**Comment by wlorenzetti** [comment]
@leolami please check fix on dev.g3wsuite.it
