### ISSUE TITLE
Table row inconsistency

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-admin#260]
https://v32.g3wsuite.it/it/map/geomarketing/qdjango/107/

Opening the pharmacy table he tells me:

Display 1 to 10 on 195 lines

But there are 20 pages of 10 records each, that is about 2,000 records

**Comment by volterra79** [comment]
@leolami 20 pages of 10 element are about 200 not 2000 records so it's right. Can you confirm?

**Comment by leolami** [comment]
Sono briao
