### ISSUE TITLE
[Layer error]-- Missing data file for layer

### ISSUE THREAD

**Issue by paolomartinis** [g3w-suite/g3w-admin#262]
When I try to upload a new project that uses "local" files the system says me:

[Layer error]-- Missing data file for layer dtm_6708 which should be located at /shared-volume/media/temp_uploads/test01/test02/dtm_6708.gpkg

![image](https://user-images.githubusercontent.com/40235048/122581627-8a8a8c80-d057-11eb-8cef-8b018c5d8b2a.png)

I uploaded the files with the file manager and they are actually uploded in the /tmp/shared-volume-g3wsuite-dev/**project_data**/test01/test02 directory, not in the /tmp/shared-volume-g3wsuite-dev/**media/temp_uploads**/test01/test02/ directory.

I'm using the docker containerized version.

**Comment by leolami** [comment]
Hi Paolo
we have to upload your data in the server througth the FileManager

You can find all the specific here:

https://g3w-suite.readthedocs.io/en/v.3.2.x/datamanagement.html

Let me know for any other problems

**Comment by paolomartinis** [comment]
> Hi Paolo
> we have to upload your data in the server througth the FileManager
> 
> You can find all the specific here:
> 
> https://g3w-suite.readthedocs.io/en/v.3.2.x/datamanagement.html
> 
> Let me know for any other problems

I've done it: I uploaded the files but the system puts them in the /tmp/shared-volume-g3wsuite-dev/project_data directory:
![image](https://user-images.githubusercontent.com/40235048/122748040-0bca6500-d28c-11eb-86f3-ad9064c3a517.png)

when I make a new project and upload a *.qgs file, it searches for dependencies at /tmp/shared-volume-g3wsuite-dev/media/temp_uploads directory, I think because the qgs file is uploaded there:
![image](https://user-images.githubusercontent.com/40235048/122748374-6794ee00-d28c-11eb-86a3-8a9903832828.png)

![image](https://user-images.githubusercontent.com/40235048/122748555-9e6b0400-d28c-11eb-814d-de362578cfff.png)

**Comment by wlorenzetti** [comment]
@paolomartinis can you post here the path writed inside the qgis project file you're trying to upload in g3w-suite?

**Comment by paolomartinis** [comment]
it's a relative path starting from the *.qgs file directory:

```
    </layer-tree-layer>
    <layer-tree-layer id="dtm_6708_2e7edb6d_92a2_4772_b7ae_74151dcdc16d" expanded="0" providerKey="gdal" legend_exp="" checked="Qt::Checked" legend_split_behavior="0" patch_size="-1,-1" source="./test01/test02/dtm_6708.gpkg" name="dtm_6708">
```

**Comment by wlorenzetti** [comment]
@paolomartinis as is writed on online documentation, your local project it must have a relative/absolute path to a local storage called `project_data`, infact the  'project_data' is the key path for g3w-suite to locate `remote` server file inside that your are uploaded into `file manage` section.. I hope I was clear.
So to work your project could be has paths like this:
source="./project_data/test01/test02/dtm_6708.gpkg"

**Comment by paolomartinis** [comment]
i missed it, sorry... it works! thanks.
Paolo
