### ISSUE TITLE
Client legend position

### ISSUE THREAD

**Issue by wlorenzetti** [g3w-suite/g3w-admin#269]
Add a select option control on project form to set legend rendering position:

- tab (default value, legend is rendered into a separate tab)
- toc (legend is rendered inside layers toc)

**Comment by leolami** [comment]
Remove the repeated title in the legend

**Comment by leolami** [comment]
Do not display the legend if the 'Do not display the legend for this layer' option is enabled on the admin side

**Comment by volterra79** [comment]
@leolami fixed

**Comment by leolami** [comment]
It remains to remove the title and space (if possible)

**Comment by wlorenzetti** [comment]
Fix 

> Remove the repeated title in the legend
