### ISSUE TITLE
Various

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-admin#275]
**Graphics**: 
- manage filters by map and by select on tables 1: N child in the case that charts on parents are not active.
For example, if [here ](https://dev.g3wsuite.it/en/map/g3w-suite-demo/qdjango/97/) you switch on **only** the charts _Cost analysis_ you cannot active filter by map or by select parent features

**Attribute tables**: 
- open the 1: N related tables with the possibility of zooming in to the parent feature clicking on a child records (consider the case in which the children are geometric features)

**Admin options load project:**
- define control mode as Multiple queries by default

**Admin download layer setup**
Would it be possible to manage the download of layers without using a checkbox for each format?
Also to reduce the icons / checkboxes that will increase more and more

**Comment by wlorenzetti** [comment]
Old issue closed.
