### ISSUE TITLE
Editing problem hiding attribute tables

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-admin#277]
If I hide the attribute tables of a layer involved in the editng of another layer (for example with the relation widget) I cannot see the list of the value of the first layer

For example:
https://dev.g3wsuite.it/en/map/g3w-suite-demo/qdjango/97/

Try to edit buildings and see the problem on the address layer

Can we resolve in anyway or does the admin need to consider this when setting up the project?

**Comment by volterra79** [comment]
@leolami solved. Check and close issue. Thanks
