### ISSUE TITLE
Update error with data in 4326

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-admin#281]
https://dev.g3wsuite.it/en/map/gsk/qdjango/143/

When I update attribute of a feature on the layer CAP and I save, the geometry undergoes an x / y coordinate inversion and is then moved to another location

If you have to test it, wait tomorrow please

**Comment by wlorenzetti** [comment]
@leolami try again updated QGIS server from 3.16.7 to 3.16.10.
