### ISSUE TITLE
Relation icon on 1:N relation table

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-admin#282]
https://v32.g3wsuite.it/en/map/geomarketing/qdjango/121/

I query the later demo_territori and see the **Relation** Tab where there are two relations
![immagine](https://user-images.githubusercontent.com/4012899/131813454-cc87dc9d-f155-4cf4-82c6-ed36772963fb.png)

I click on CAP relation and then I open the detail of a record on the **Relation** TAB
Infact CAP layer have a 1:N relation with Farmacie

![immagine](https://user-images.githubusercontent.com/4012899/131813948-573f377a-8c12-4ab0-9f84-56078b3ef14e.png)

We see the link to the new 1:N relation table, but it does'n work

Two solution:

- Delete icon
- Make the link work

Choose the fastest way

**Comment by volterra79** [comment]
@leolami i can't see the charts icon. Can you check again?

**Comment by leolami** [comment]
I see it in Chrome and Firefox....

Have you follow the exact workflow?
