### ISSUE TITLE
Decimal number format

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-admin#283]
https://v32.g3wsuite.it/it/map/geomarketing/qdjango/121/

Se interroghi la mappa e vai a vedere la scheda info del layer 'demo_territori' vedrai che i campi decimali vengono presentati con un numero elevato di decimali....

![image](https://user-images.githubusercontent.com/4012899/131967550-8ebca74b-bba8-4916-b502-47aeb7606768.png)

Se però interrogo da QGIS in realtà ne vedo solo due

Se possibile sarebbe da:

- ridurre i decimali mostrati (2?)
- formattare i numeri con i punti relativi alle migliaia per facilitare la lettura (da valutare, non sempre idoneo)

**Comment by wlorenzetti** [comment]
@leolami this issue can be closed?
