### ISSUE TITLE
Error on attribute table filter

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-admin#284]
https://v32.g3wsuite.it/it/map/geomarketing/qdjango/121/

Here I try to make a filter on the cap_aggregati attribute filter

Field: CAP
Value: 15017

But the result is not correct:

![image](https://user-images.githubusercontent.com/4012899/131989043-26fb6280-d3e5-4c4f-9c42-ebaf3e620e59.png)

**Comment by wlorenzetti** [comment]
@leolami I just try but response is correct, if I try on QGIS desktop 15017 I didn't find nothing as on G3W-SUITE response is empty.

**Comment by leolami** [comment]
But if the response is empity I must have a empity table...

And not a table with all the values as in the example

**Comment by leolami** [comment]
It works...., sorry

the table is correctly empity

**Comment by wlorenzetti** [comment]
I get an empty table:
![Schermata da 2021-09-08 11-38-09](https://user-images.githubusercontent.com/196809/132485806-6bacae76-f1a4-4237-ae1c-e96ae698ecd0.png)
