### ISSUE TITLE
Admin layer list

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-admin#291]
**Admin layer tools:** reoreder in this way
![immagine](https://user-images.githubusercontent.com/4012899/130043129-1fe1acab-b61d-45e5-9b1a-fde24d5fcd4a.png)

and change info popup:
- _Fillter by user/groups:_ Hide layer by user/groups
- _Manage geo-constraints list:_ Geo-constraints by user/group
- _Manage alphanumeric visualization and editing constraints:_ Alphanumeric and QGIS expressions constraints by user/groups

**Comment by wlorenzetti** [comment]
@leolami done.
