### ISSUE TITLE
Editing: remove vertex of a polygon

### ISSUE THREAD

**Issue by lucamanga** [g3w-suite/g3w-admin#299]
Hello,

if we edit a polygon, we can move and add vertexes but we cannot remove them.
Can you add this feature?

**Comment by leolami** [comment]
Of course, but we need to wait next vers 3.4

**Comment by volterra79** [comment]
@lucamanga you can remove a vertex pressing Alt key and click on vertex. Please let me know.

**Comment by lucamanga** [comment]
it works! Thank you :-)
