### ISSUE TITLE
Layers not avilable

### ISSUE THREAD

**Issue by moovida** [g3w-suite/g3w-admin#305]
I am able to see my loaded layers in the layers list, but then they are not visible in map.  

![image](https://user-images.githubusercontent.com/390250/138466307-fe3b7c20-5f2b-4a52-abb9-122e298392df.png)

Is there a way to check the reason? In the console I can't see any error.

Zooming to layer works. 

The attributes table opens properly and the selected records are highlighted in the map.

If I click on an invisible geometry with the info tool, I get: 

![image](https://user-images.githubusercontent.com/390250/138467241-646b1732-6c0f-4567-a485-027d18175575.png)

**Comment by volterra79** [comment]
@moovida can you share the project or layers to test and check the issue? Thanks

**Comment by wlorenzetti** [comment]
Some questions:
What is your QGIS version?
What kind of type your data are?

Do you have any errors into your 'runserve'r console?

**Comment by moovida** [comment]
Hi @wlorenzetti  and @volterra79:

1. QGIS 3.20
2. these are the very standard data from the natural earth project. Shapefiles
3. no errors in the console. Not that I would see any at least

I attach the zip of the shapes and the qgis project.

Data:
[project_data.tar.gz](https://github.com/g3w-suite/g3w-admin/files/7398096/project_data.tar.gz)
Project (change zip extension back to qgz):
[g3wtest.zip](https://github.com/g3w-suite/g3w-admin/files/7398165/g3wtest.zip)

**Comment by volterra79** [comment]
@moovida i'll let you know. Thanks

**Comment by volterra79** [comment]
@moovida i test with qgis 3.16.11 and all is ok. Can you share the response returned from server (using network tab of browser development tool) when query ne_10m_admin_1_states_provinces? 
![Screenshot from 2021-10-22 16-33-20](https://user-images.githubusercontent.com/1051694/138472951-c3b223f8-6a11-455e-96af-59808b400fcc.png)

Thanks

**Comment by moovida** [comment]
Hi @volterra79 , due to my ubuntu impish install I am not able to install different QGIS than 3.20.
At the current time, when I enable to info button, I get something like this in the browser console:

```
app.982d520b293ab481427a9b84a3e378da.min.js:10 Uncaught TypeError: Cannot read properties of null (reading 'getSource')
    at r.o._showMarker (app.982d520b293ab481427a9b84a3e378da.min.js:10)
    at r.<anonymous> (app.982d520b293ab481427a9b84a3e378da.min.js:10)
    at r.e (vendor.a74acef6c1ecebde4a905f2a77c311cc.min.js:22922)
    at r.e.dispatchEvent (vendor.a74acef6c1ecebde4a905f2a77c311cc.min.js:22922)
    at r.c.toggle (app.982d520b293ab481427a9b84a3e378da.min.js:10)
    at app.982d520b293ab481427a9b84a3e378da.min.js:10
    at e.forEach (vendor.a74acef6c1ecebde4a905f2a77c311cc.min.js:22922)
    at a.s._handleClick (app.982d520b293ab481427a9b84a3e378da.min.js:10)
    at a.c._handleClick (app.982d520b293ab481427a9b84a3e378da.min.js:10)
    at HTMLDivElement.dispatch (vendor.a74acef6c1ecebde4a905f2a77c311cc.min.js:3)
```

and when I click on the map:

```
app.982d520b293ab481427a9b84a3e378da.min.js:6 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'featureMember')
    at i.m._getHandledResponsesFromResponse (app.982d520b293ab481427a9b84a3e378da.min.js:6)
    at i.m.handleQueryResponseFromServer (app.982d520b293ab481427a9b84a3e378da.min.js:6)
    at app.982d520b293ab481427a9b84a3e378da.min.js:6
```

then things like these appear in the terminal in which I launched the server:

```
cannot unpack non-iterable NoneType object
cannot unpack non-iterable NoneType object
[25/Oct/2021 13:13:07] "GET /ows/1/qdjango/1/?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=ne_10m_admin_0_countries%2Cne_10m_admin_1_states_provinces%2Cne_10m_roads%2Cne_10m_populated_places&SLD_VERSION=1.1.0&DPI=96&STYLES=default%2Cdefault%2Cdefault%2Cdefault&CRS=EPSG%3A4326&WIDTH=305&HEIGHT=700&BBOX=29.259995914318306%2C7.3151337042746825%2C53.30853249058069%2C17.793424641074722 HTTP/1.1" 403 0
[25/Oct/2021 13:13:07] "GET /ows/1/qdjango/1/?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=ne_10m_admin_0_countries%2Cne_10m_admin_1_states_provinces%2Cne_10m_roads%2Cne_10m_populated_places&SLD_VERSION=1.1.0&DPI=96&STYLES=default%2Cdefault%2Cdefault%2Cdefault&CRS=EPSG%3A4326&WIDTH=655&HEIGHT=700&BBOX=29.259995914318306%2C1.3029995602090878%2C53.30853249058069%2C23.80555878514032 HTTP/1.1" 403 0
cannot unpack non-iterable NoneType object
cannot unpack non-iterable NoneType object
...
```

The server response I get to this request:

```
http://127.0.0.1:8000/ows/1/qdjango/1/?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetFeatureInfo&CRS=EPSG:4326&QUERY_LAYERS=ne_10m_admin_1_states_provinces&INFO_FORMAT=application/vnd.ogc.gml&FEATURE_COUNT=5&FI_POINT_TOLERANCE=10&FI_LINE_TOLERANCE=10&FI_POLYGON_TOLERANCE=10&G3W_TOLERANCE=0.08035714285714285&WITH_GEOMETRY=true&I=327&J=350&DPI=96&WIDTH=655&HEIGHT=700&STYLES=&BBOX=40.16911719398339,9.953476943649163,45.79411719398339,15.21686980079202
```

 is:

```xml
<ServiceExceptionReport xmlns="http://www.opengis.net/ogc" version="1.3.0">
 <ServiceException code="Service configuration error">Service unknown or unsupported. Current supported services (case-sensitive): WMS WFS WCS WMTS SampleService, or use a WFS3 (OGC API Features) endpoint</ServiceException>
</ServiceExceptionReport>
```

I am currently waiting for the latest qgis ltr version to come out, which will hopefully be packaged for ubuntu impish. At the current time, even if impish is listed, it is not supported (see https://github.com/qgis/QGIS/issues/45641).

**Comment by volterra79** [comment]
@moovida it seems that  there is a problem of  **HTTP 403 Forbidden**. Are you log in?

**Comment by moovida** [comment]
To be honest I do not remember if I ever had to login once at the very begin, but I assume yes due to this:

![image](https://user-images.githubusercontent.com/390250/138704990-313203d1-47e7-44e5-a4b4-2d242a4df606.png)

**Comment by volterra79** [comment]
@moovida maybe is a problem of apache/qgis_mapserv.fcgi permission.
Below apache site configuration:

ScriptAlias /cgi-bin/ /usr/lib/cgi-bin/
        <Directory "/usr/lib/cgi-bin/">
          AllowOverride None
          Options +ExecCGI -MultiViews -SymLinksIfOwnerMatch
          Order allow,deny
          Allow from all
          Require all granted
        </Directory>

but maybe @wlorenzetti have a solution.

**Comment by moovida** [comment]
Hi @volterra79 , where should I find this config? I still have to wrap my head around the project structure.

**Comment by sindile** [comment]
> Hi @volterra79 , due to my ubuntu impish install I am not able to install different QGIS than 3.20. At the current time, when I enable to info button, I get something like this in the browser console:
> 
> ```
> app.982d520b293ab481427a9b84a3e378da.min.js:10 Uncaught TypeError: Cannot read properties of null (reading 'getSource')
>     at r.o._showMarker (app.982d520b293ab481427a9b84a3e378da.min.js:10)
>     at r.<anonymous> (app.982d520b293ab481427a9b84a3e378da.min.js:10)
>     at r.e (vendor.a74acef6c1ecebde4a905f2a77c311cc.min.js:22922)
>     at r.e.dispatchEvent (vendor.a74acef6c1ecebde4a905f2a77c311cc.min.js:22922)
>     at r.c.toggle (app.982d520b293ab481427a9b84a3e378da.min.js:10)
>     at app.982d520b293ab481427a9b84a3e378da.min.js:10
>     at e.forEach (vendor.a74acef6c1ecebde4a905f2a77c311cc.min.js:22922)
>     at a.s._handleClick (app.982d520b293ab481427a9b84a3e378da.min.js:10)
>     at a.c._handleClick (app.982d520b293ab481427a9b84a3e378da.min.js:10)
>     at HTMLDivElement.dispatch (vendor.a74acef6c1ecebde4a905f2a77c311cc.min.js:3)
> ```
> 
> and when I click on the map:
> 
> ```
> app.982d520b293ab481427a9b84a3e378da.min.js:6 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'featureMember')
>     at i.m._getHandledResponsesFromResponse (app.982d520b293ab481427a9b84a3e378da.min.js:6)
>     at i.m.handleQueryResponseFromServer (app.982d520b293ab481427a9b84a3e378da.min.js:6)
>     at app.982d520b293ab481427a9b84a3e378da.min.js:6
> ```
> 
> then things like these appear in the terminal in which I launched the server:
> 
> ```
> cannot unpack non-iterable NoneType object
> cannot unpack non-iterable NoneType object
> [25/Oct/2021 13:13:07] "GET /ows/1/qdjango/1/?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=ne_10m_admin_0_countries%2Cne_10m_admin_1_states_provinces%2Cne_10m_roads%2Cne_10m_populated_places&SLD_VERSION=1.1.0&DPI=96&STYLES=default%2Cdefault%2Cdefault%2Cdefault&CRS=EPSG%3A4326&WIDTH=305&HEIGHT=700&BBOX=29.259995914318306%2C7.3151337042746825%2C53.30853249058069%2C17.793424641074722 HTTP/1.1" 403 0
> [25/Oct/2021 13:13:07] "GET /ows/1/qdjango/1/?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=ne_10m_admin_0_countries%2Cne_10m_admin_1_states_provinces%2Cne_10m_roads%2Cne_10m_populated_places&SLD_VERSION=1.1.0&DPI=96&STYLES=default%2Cdefault%2Cdefault%2Cdefault&CRS=EPSG%3A4326&WIDTH=655&HEIGHT=700&BBOX=29.259995914318306%2C1.3029995602090878%2C53.30853249058069%2C23.80555878514032 HTTP/1.1" 403 0
> cannot unpack non-iterable NoneType object
> cannot unpack non-iterable NoneType object
> ...
> ```
> 
> The server response I get to this request:
> 
> ```
> http://127.0.0.1:8000/ows/1/qdjango/1/?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetFeatureInfo&CRS=EPSG:4326&QUERY_LAYERS=ne_10m_admin_1_states_provinces&INFO_FORMAT=application/vnd.ogc.gml&FEATURE_COUNT=5&FI_POINT_TOLERANCE=10&FI_LINE_TOLERANCE=10&FI_POLYGON_TOLERANCE=10&G3W_TOLERANCE=0.08035714285714285&WITH_GEOMETRY=true&I=327&J=350&DPI=96&WIDTH=655&HEIGHT=700&STYLES=&BBOX=40.16911719398339,9.953476943649163,45.79411719398339,15.21686980079202
> ```
> 
> is:
> 
> ```
> <ServiceExceptionReport xmlns="http://www.opengis.net/ogc" version="1.3.0">
>  <ServiceException code="Service configuration error">Service unknown or unsupported. Current supported services (case-sensitive): WMS WFS WCS WMTS SampleService, or use a WFS3 (OGC API Features) endpoint</ServiceException>
> </ServiceExceptionReport>
> ```
> 
> I am currently waiting for the latest qgis ltr version to come out, which will hopefully be packaged for ubuntu impish. At the current time, even if impish is listed, it is not supported (see [qgis/QGIS#45641](https://github.com/qgis/QGIS/issues/45641)).

HI @moovida  - use the instructions from here to install 3.16 using Conda - https://gisunchained.wordpress.com/2019/05/29/using-qgis-from-conda/

**Comment by wlorenzetti** [comment]
Hi @sindile did you install qgis-server apt package?

**Comment by sindile** [comment]
> Hi @sindile did you install qgis-server apt package?

Hi @wlorenzetti , no I only install qgis-desktop 3.16 via Conda and use  [g3wsuite-docker](https://github.com/elpaso/g3w-suite-docker)

**Comment by moovida** [comment]
@sindile , that was the same issue I had. You need to install the qgis-server package manually also.
