### ISSUE TITLE
Application path not initialized - Could not connect to any X display

### ISSUE THREAD

**Issue by spaciandd** [g3w-suite/g3w-admin#313]
Following are log on,

```sh
paver install
```

```sh
python g3w-admin/manage.py migrate --noinput
Application path not initialized
qt.qpa.screen: QXcbConnection: Could not connect to display
Could not connect to any X display.
```

Captured Task Output:
---------------------

```
---> pavement.install
---> pavement.install_yarn_components

Installing Yarn/Bower components...
yarn --ignore-engines --ignore-scripts --prod
node -e "try { require('fs').symlinkSync(require('path').resolve('node_modules/@bower_components'), 'g3w-admin/core/static/bower_components', 'junction') } catch (e) { }"
Yarn/Bower components installed.

---> pavement.requirements
Installing Python modules...
pip install -r requirements.txt
pip install -r requirements_huey.txt
Python modules installed.

---> pavement.sync
python g3w-admin/manage.py migrate --noinput

Build failed running pavement.install: Subprocess return code: 1
```

**Comment by spaciandd** [comment]
These are two separate issues, I found a solution for "Could not connect to any X display", you just need to run following command,
`export DISPLAY=:99`

**Comment by wlorenzetti** [comment]
Hi @spaciandd I suggest you to try docker version, in particular the v3.3.x branch last stable version: https://github.com/g3w-suite/g3w-suite-docker/tree/v3.3.x

**Comment by spaciandd** [comment]
### 502 Bad Gateway
I am getting bad gateway, while accessing at port 8080

## **.env** updated to,
```
# External hostname, for docker internal network aliases
WEBGIS_PUBLIC_HOSTNAME=demo.g3wsuite.it

# This volume is persistent and mounted by all
# containers as /shared-volume
WEBGIS_DOCKER_SHARED_VOLUME=shared-volume-g3w-suite


# DB setup
G3WSUITE_POSTGRES_USER_LOCAL=g3wsuite
G3WSUITE_POSTGRES_PASS=test
G3WSUITE_POSTGRES_DBNAME=g3wsuite
G3WSUITE_POSTGRES_HOST=postgis
G3WSUITE_POSTGRES_PORT=5432

# Caching
G3WSUITE_TILECACHE_PATH=/shared-volume/tile_cache/
TILESTACHE_CACHE_BUFFER_SIZE=256
TILESTACHE_CACHE_TOKEN=374h5g96831hsgetvmkdel

# URL of the QGIS Server
G3WSUITE_QDJANGO_SERVER_URL=http://qgisserver/ows/

# Set G3W-SUITE debug state
G3WSUITE_DEBUG = 1 (0 default)

# Gunicorn workers (default to 8)
G3WSUITE_GUNICORN_NUM_WORKERS=8

# Openrouteservice (if enabled in custom settings)
G3WSUITE_ORS_API_ENDPOINT='https://api.openrouteservice.org/v2'
G3WSUITE_ORS_API_KEY='<your API key, if required (optional)>'

```

## Running following commands,

```
docker build --build-arg G3W_SUITE_BRANCH=v.3.3.x -f Dockerfile.g3wsuite.dockerfile -t g3wsuite/g3w-suite:v3.3.x --no-cache .
docker build -f Dockerfile.g3wsuite-deps.ltr.dockerfile -t g3wsuite/g3w-suite-deps-ltr:v3.3.x --no-cache .
docker build -f Dockerfile.postgis.dockerfile -t g3wsuite/postgis:11.0-2.5 .
docker-compose up -d
```

Also I have updated `config/ngnix/django.conf`, i.e., replaced the server_name, server_name demo.g3wsuite.it;

**Comment by wlorenzetti** [comment]
what say the docker-compose logs g3w-suite

**Comment by spaciandd** [comment]
```
[1/4] Resolving packages...
g3w-suite_1  | success Already up-to-date.
g3w-suite_1  | Done in 0.21s.
g3w-suite_1  | { Error: EEXIST: file already exists, symlink '/code/node_modules/@bower_components' -> 'g3w-admin/core/static/bower_components'
g3w-suite_1  |     at Object.symlinkSync (fs.js:909:3)
g3w-suite_1  |     at [eval]:1:21
g3w-suite_1  |     at Script.runInThisContext (vm.js:122:20)
g3w-suite_1  |     at Object.runInThisContext (vm.js:329:38)
g3w-suite_1  |     at Object.<anonymous> ([eval]-wrapper:6:22)
g3w-suite_1  |     at Module._compile (internal/modules/cjs/loader.js:778:30)
g3w-suite_1  |     at evalScript (internal/bootstrap/node.js:590:27)
g3w-suite_1  |     at startup (internal/bootstrap/node.js:265:9)
g3w-suite_1  |     at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
g3w-suite_1  |   errno: -17,
g3w-suite_1  |   syscall: 'symlink',
g3w-suite_1  |   code: 'EEXIST',
g3w-suite_1  |   path: '/code/node_modules/@bower_components',
g3w-suite_1  |   dest: 'g3w-admin/core/static/bower_components' }
g3w-suite_1  | Setup was already done, skipping ...
g3w-suite_1  | wait-for-it: waiting 60 seconds for postgis:5432

```

**Comment by spaciandd** [comment]
> what say the docker-compose logs g3w-suite

Found following on stackoverflow and seems valid answer as after some time **502 Bad Gateway** vanishes, but now getting **500 Internal Error**
https://stackoverflow.com/a/63873062/9150786
> It's most likely a timing issue: your application is trying to connect to the database before the database is ready. The easiest solution here is probably to just set a restart policy on your application container, so that docker will restart it when it fails. You might as well get rid of the depends-on directive, because this is functionally useless: while docker knows when the database container is up, it knows nothing about the state of the database application itself.

For **500 Internal Error**, logs for g3w-suite are,
```
[2022-01-21 17:04:08 +0000] [203] [DEBUG] GET /
Internal Server Error: /
[2022-01-21 17:04:08 +0000] [203] [DEBUG] GET /favicon.ico
Internal Server Error: /favicon.ico
```

Seems like favicon error, how should I resolve this ? @wlorenzetti

**Comment by wlorenzetti** [comment]
It seems that your docker postgis container is not running. 
Delete the current docker image 
`docker rmi g3wsuite/postgis:11.0-2.5`
and try again `docker-compose up -d` so docker try to download it from docker hub

**Comment by spaciandd** [comment]
> It seems that your docker postgis container is not running. Delete the current docker image `docker rmi g3wsuite/postgis:11.0-2.5` and try again `docker-compose up -d` so docker try to download it from docker hub

WoW. It worked. So I should not build postgis myself ? i.e., not to run following command,
`docker build -f Dockerfile.postgis.dockerfile -t g3wsuite/postgis:11.0-2.5 .`

**Comment by wlorenzetti** [comment]
Usualy I build docker image in this way but it's be a while that this build doesn't a correct image, I'll verify it very soon.
