### ISSUE TITLE
Provide a setting to change WMS GetMap `IMAGE_QUALITY`

### ISSUE THREAD

**Issue by lucamanga** [g3w-suite/g3w-admin#314]
Hello,

it seems that in G3W Suite the generated map images are in PNG format with 8 bit quality.
I would like to test various format/quality settings.

See the official QGIS documentation:

https://docs.qgis.org/2.18/it/docs/user_manual/working_with_ogc/server/services.html#getmap

we have:

-  **IMAGE_QUALITY**
- **image/png; mode=** can be 16bit or 8bit

**Comment by lucamanga** [comment]
Addendum, could you provide an option for:
 - JPEG format, setting the quality (from 1 to 100)
 - PNG format, 8 or 16 bit

**Comment by wlorenzetti** [comment]
@lucamanga thanks for suggestion :) We'll improve it into next release

**Comment by tudorbarascu** [comment]
Indeed, was just looking for this feature. It's very important if you're outside, with low network bandwith, to be able tu request in jpeg.

https://docs.qgis.org/3.22/it/docs/server_manual/services/wms.html#wms-getmap-format

Also it would be nice to have a WMS hidpi option for whether to honor DPI or not, important for high resolution devices as it saves a lot of bandwith -> greater speed for the site/user.
