### ISSUE TITLE
3.4: Editing: G3WSUITE users management

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-admin#317]
Editing: user insertion creating / modifying records of a layer in predefined fields

ADMIN side

In the editing activation form it is necessary to define:
- a field to be filled in by the user who creates the records
- a field to be filled in with the user modifying the records

**Comment by leolami** [comment]
In questi campi va messo solo utente

Non utente + data

La data la gestiamo, se serve a parte con l'espressione now

Puoi modificare prima del branch? 

Grazie

**Comment by wlorenzetti** [comment]
Done
