### ISSUE TITLE
 3.4: Project order definition on frontend

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-admin#318]
On the ADMIN side it would be necessary to be able to define the order of projects (currently alphabetical) and that this order is reflected in the frontend

Development paid for by Parco Casentino for 3.4

**Comment by wlorenzetti** [comment]
Done, now is possible change project list order inside a group by drag and drop
![Schermata da 2022-03-08 07-33-26](https://user-images.githubusercontent.com/196809/157182279-2fcd6713-88d7-4178-867b-ab9754b6425f.png)

**Comment by leolami** [comment]
To try it I need the FrontEnd

Can tou install it?

So I can prepare also the 3.4 demo
