### ISSUE TITLE
TemporalControl with NetCDF

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-admin#328]
I am trying to load a project containing a NetCDF raster and I get this error:

[Project error on layers()]-- [Layer error on layerType(runof_sfc_mon_mean_1ee61df9_0ba0_43f0_a397_5af947714567)]-- Mancante o tipo di layer non valido "mdal" 

I enclose the project and data

[G3WSUITE_TEMPORAL.zip](https://github.com/g3w-suite/g3w-admin/files/8223018/G3WSUITE_TEMPORAL.zip)

**Comment by wlorenzetti** [comment]
@leolami but is not a netCDF raster layer is a vector layer.

**Comment by leolami** [comment]
No runof_sfc_mon_mean.nc è un raster...

**Comment by leolami** [comment]
Allora il problema sembra che sia legato alla gestione dei NetCDF da parte di QGIS **3.22**

In pratica lo stesso raster lo posso caricare come RASTER e come MESH e il bello è che vedo due cose copletamente diverse....

Comunque...

In pratica se carico su QGIS il raster runof_sfc_mon_mean.nc come **MESH** il Temporal Controller di QGIS funziona

Se lo carico come **RASTER** no

Viceversa su G3W-SUITE se uso il progetto con il dato caricato come raster il time series funziona...

Ora qui allego un pacchetto con dati e progetti QGIS, poi vediamo insieme...

[temporal.zip](https://github.com/g3w-suite/g3w-admin/files/8261604/temporal.zip)

**Comment by leolami** [comment]
https://dev.g3wsuite.it/it/groups/time-series/projects/

**Comment by leolami** [comment]
This library appears to be needed

https://github.com/lutraconsulting/MDAL

**Comment by wlorenzetti** [comment]
Close for change base system.
