### ISSUE TITLE
Editing: crash with calendar

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-admin#334]
https://dev.g3wsuite.it/it/map/g3w-suite-demo/qdjango/97/

If I try to edit a building and choose a date from the calendar everything crashes

![immagine](https://user-images.githubusercontent.com/4012899/159905707-e23cbfc6-671a-404b-af39-2a4bf4acd02a.png)

**Comment by leolami** [comment]
![immagine](https://user-images.githubusercontent.com/4012899/160085284-43a5b9c1-f53c-408d-a2ca-7632332a57ae.png)

**Comment by volterra79** [comment]
fixed
