### ISSUE TITLE
Editing icon in attribute form (minor bug)

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-admin#336]
If you access the attribute form via a parameterized URL, the pen icon does not appear on the form

https://dev.g3wsuite.it/it/map/g3w-suite-demo/qdjango/97/?zoom_to_fid=buildings_2f43dc1d_6725_42d2_a09b_dd446220104a%7C1

**Comment by volterra79** [comment]
fixed

**Comment by volterra79** [comment]
fixed
