### ISSUE TITLE
N:M relations

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-admin#337]
https://dev.g3wsuite.it/it/map/test-db/qdjango/185/

Search: **Areoporto ID** - ID: **4**

Then clik on Relations **Areoporti NM**

You have this results (all the airlines):

![immagine](https://user-images.githubusercontent.com/4012899/160237752-f6ef6979-8d60-4fe7-8926-5596f6f51f03.png)

But in the intermediate table (relazione_nm) we have not any record with id_areo = 4

![immagine](https://user-images.githubusercontent.com/4012899/160237811-073544bb-96d6-4a74-b37e-6cb5111c76be.png)

Can you check it?

**Comment by volterra79** [comment]
Fixed
