### ISSUE TITLE
Attribute table showing multiple times the same record

### ISSUE THREAD

**Issue by gacarrillor** [g3w-suite/g3w-admin#348]
Hi!

Just encountered a small bug when opening an attribute table in a project.

There is one single record shown repeatedly in the first page.

![image](https://user-images.githubusercontent.com/652785/169314578-2cebe3e9-2239-4519-b0c3-55327338383c.png)

It occurs with all my layers (data source: GPKG) when they have more than 10 features, i.e., when the results are paginated.

The repeated record is always the `fid=10`.

Any idea of why it happens?

I'm using G3W-SUITE Version 3.5.dev-20220517145638 from https://github.com/g3w-suite/g3w-suite-docker

Thanks a lot for G3W-SUITE! :clap:

**Comment by gacarrillor** [comment]
By the way, if I go to page 2 (where everything is alright) and go back to page 1, then I can see the records correctly:

![image](https://user-images.githubusercontent.com/652785/169316988-e29c4a1b-9f2b-44d0-8fa0-f1b2e7743fbf.png)

**Comment by wlorenzetti** [comment]
Hi @gacarrillor,
it's the first time I've seen such a bug :). We should see if it is a webgis client or server error.
Could you report here tha call to API REST to the server?

On browser debug (F12 usually) on xhr calls you should find a call like the follow:
http://<your_domain>/vector/api/data/qdjango/225/test_f613f747_17b2_4f99_8308_ef4cd176f743/?page=1&page_size=10&ordering=id&formatter=1

**Comment by gacarrillor** [comment]
In my case: 

`http://localhost:8080/vector/api/data/qdjango/1/lote_247f06ed_6935_448a_b89b_e0c54116db62/?page=1&page_size=10&ordering=fid&formatter=1`

returns the results correctly in GeoJSON:

![image](https://user-images.githubusercontent.com/652785/169336342-3430a706-a793-477a-b615-9b3f7b63970a.png)

Then it should be on the client side.

**Comment by wlorenzetti** [comment]
@volterra79 can you check?

**Comment by volterra79** [comment]
@gacarrillor can you provide us a GPKG file to check. Thanks

**Comment by volterra79** [comment]
@gacarrillor i replicate the issue. I fix it and let you know.Thanks

**Comment by volterra79** [comment]
@gacarrillor Fixed. can you try now. Please let me know. Thanks

**Comment by gacarrillor** [comment]
Confirmed @volterra79!

Thanks to you and to @wlorenzetti
