### ISSUE TITLE
Projects with memory layers cannot be uploaded although they're set to be ignored in the Server properties

### ISSUE THREAD

**Issue by tudorbarascu** [g3w-suite/g3w-admin#355]
Hello

When uploading a project that contains a memory layer it errors out with:
```
[Project error on layers()]-- [Layer error on layerType(...)]-- Missing or invalid type for layer "memory"
```

As the layer is ignored in the QGIS Server tab, I think it shouldn't have errored out and should have been ignored.

Of course, removing the memory layer is one way of handling it.

All the best.

**Comment by wlorenzetti** [comment]
Thanks @tudorbarascu
