### ISSUE TITLE
Move plugins configuration from initConfig to project config

### ISSUE THREAD

**Issue by volterra79** [g3w-suite/g3w-admin#372]
It could be better move plugin configuration from:
`
initConfig = {
...
group: {
  plugins: {
      editing: {....},
     ....
  }
}
`
to project config

`{
 id: 1,
 name: 'Project 1',
...,
plugins: {
    editing: {....}
}
}`

maybe after https://github.com/g3w-suite/g3w-admin/issues/371

**Comment by wlorenzetti** [comment]
@Raruto @volterra79 this is a very big refactoring issue!! :(
