### ISSUE TITLE
Close accomplished milestones

### ISSUE THREAD

**Issue by Raruto** [g3w-suite/g3w-admin#374]
Here there are some milestones that have been definitively completed for some time

- https://github.com/g3w-suite/g3w-admin/milestones

For example:

- [Release 3.0](https://github.com/g3w-suite/g3w-admin/milestone/1)
- [Release 3.1](https://github.com/g3w-suite/g3w-admin/milestone/2)
- [Release 3.2](https://github.com/g3w-suite/g3w-admin/milestone/3)

![immagine](https://user-images.githubusercontent.com/9614886/189131827-d5f87227-c829-4413-9cb1-ceed0db75ea5.png)

**Comment by wlorenzetti** [comment]
Done
