### ISSUE TITLE
Move `docs` folder into `g3w-suite-documentation` repository

### ISSUE THREAD

**Issue by Raruto** [g3w-suite/g3w-admin#375]
~~Nowdays many installations take advantage of docker, so it may be advisable to keep the documentation in the same place as the code used by the end users:~~

~~[`g3w-admin/docs`](https://github.com/g3w-suite/g3w-admin/blob/12024ef814cfe1c2bd56f097936521d6988e6c67/docs) --> [`g3w-suite-docker/docs`](https://github.com/g3w-suite/g3w-suite-docker)~~

To keep track of any new needed changes (aka. issues and pull requests) and possibly simplify the process of new edits by other users it's best to keep your user documentation in one dedicated place.

Ref: https://g3w-suite.readthedocs.io/

**Comment by Raruto** [comment]
Perhaps, it would be better to create a dedicated repository instead, eg: [g3w-suite/g3w-suite-documentation](https://github.com/g3w-suite/g3w-suite-documentation) ?

**Comment by Raruto** [comment]
@wlorenzetti I created a new dedicated repository with all current branches [g3w-suite/g3w-suite-documentation](https://github.com/g3w-suite/g3w-suite-documentation).

When you have some time, can you migrate current build settings to that repository and then enable the "autobuild" feature on Readthedocs? (see: https://docs.readthedocs.io/en/stable/pull-requests.html)

**Comment by wlorenzetti** [comment]
@Raruto I'm still thinking if move documentation to new and independent repository is a good idea.I'm afraid it will be more difficult to maintain over time.

**Comment by Raruto** [comment]
> @Raruto I'm still thinking if move documentation to new and independent repository is a good idea.I'm afraid it will be more difficult to maintain over time.

@wlorenzetti the project is already made up of separate modules (ie. not a "mono-repo"), also due this it is advisable to keep track of these in a dedicated "external" repository.

Although a little bit hard to find out at "first" reading (perhaps also the second and third time.. 😞), these are the logical connections between the `docs` and `code` :

- [`docker.html`](https://g3w-suite.readthedocs.io/en/v.3.4.x/docker.html) ------------> [g3w-suite-docker](https://github.com/g3w-suite/g3w-suite-docker)
- [`administration.html`](https://g3w-suite.readthedocs.io/en/v.3.4.x/g3wsuite_administration.html) ---> [g3w-admin](https://github.com/g3w-suite/g3w-admin)
- [`client.html`](https://g3w-suite.readthedocs.io/en/v.3.4.x/g3wsuite_client.html) ------------> [g3w-client](https://github.com/g3w-suite/g3w-client)
- [`editing.html`](https://g3w-suite.readthedocs.io/en/v.3.4.x/g3wsuite_editing.html) -----------> ([g3w-client-plugin-editing](https://github.com/g3w-suite/g3w-client-plugin-editing) + [g3w-admin-editing](https://github.com/g3w-suite/g3w-admin/blob/5a6b1db58f8e922cc3c0d47722c94ee241179d35/g3w-admin/editing)) \*

---

\* the whole project would be much clearer to understand if these kind of addons were released as reusable django packages, instead of separating between **`admin`** and **`client`** --> Right now you have a lot of duplicate issues and pulls and it is difficult to understand the direction that a specific module is taking, as well as all the additional complexity required to understand how to install, develop or test a specific plugin...

---

Doing like so, all these issue template files could be removed from the individual repositories:

- [g3w-suite-docker/ISSUE_TEMPLATE/improve_documentation.yml](https://github.com/g3w-suite/g3w-suite-docker/blob/0bfcdd458de462cf639daf07df83d13ce7672984/.github/ISSUE_TEMPLATE/improve_documentation.yml)

- [g3w-admin/ISSUE_TEMPLATE/improve_documentation.yml](https://github.com/g3w-suite/g3w-admin/blob/5a6b1db58f8e922cc3c0d47722c94ee241179d35/.github/ISSUE_TEMPLATE/improve_documentation.yml)

- [g3w-client/ISSUE_TEMPLATE/improve_documentation.yml](https://github.com/g3w-suite/g3w-client/blob/cf6b5d8f4402e22c479fcb536506877a59a6e757/.github/ISSUE_TEMPLATE/improve_documentation.yml)

and replaced by a dedicated `improve_documentation.yml` file (within the [g3w-documentation](https://github.com/g3w-suite/g3w-documentation) repository) and the following selector  within the same repositories:

![documentation issue](https://user-images.githubusercontent.com/9614886/197722855-94b57e9e-dcf4-4769-a99d-ebf6ae3dd946.png)

**More info:**

- [Configuring the template chooser](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser)
- [QGIS/.github/ISSUE_TEMPLATE/config.yml](https://github.com/qgis/QGIS/blob/69ee3bc0d39cd907c827da6b38e8c1348ff931c5/.github/ISSUE_TEMPLATE/config.yml)
