### ISSUE TITLE
QPlotly plugin shows `[object Object]` as chart labels

### ISSUE THREAD

**Issue by Raruto** [g3w-suite/g3w-admin#377]
As per **v3.5-dev20220913**, this is you what you get on the official demo: https://dev.g3wsuite.it/en/map/demo-34/

![immagine](https://user-images.githubusercontent.com/9614886/189902609-968e50fc-1d02-49ba-ac28-d65375475e26.png)

Maybe related to: https://github.com/g3w-suite/g3w-admin/commit/458c8bec11864ef29b9a14291231fb0543f11b77 and https://github.com/g3w-suite/g3w-admin/commit/722002452af003b03c7328418a18523928abd6c9

**Comment by wlorenzetti** [comment]
@Raruto on v3.4 qplotly is at version 2.5.1 (https://github.com/g3w-suite/g3w-admin/blob/v.3.4.x/g3w-admin/qplotly/requirements.txt) and plot title property for G3W-CLIENT is not change, perhaps into dev branh that use plotly a version 5.8.0 it changed, I've to check.

**Comment by wlorenzetti** [comment]
@volterra79 where from qplotly plugin initConfig property G3W-CLIENT takes the title value for Charts Plots section

![Screenshot_20221010_093426](https://user-images.githubusercontent.com/196809/194817759-bb2fc0f6-2708-483f-b009-64f2ad0a8e6e.png)

and for showing chart area?

![Screenshot_20221010_093433](https://user-images.githubusercontent.com/196809/194817928-b7aa1f8c-99cd-46bf-a762-59b0d75e9b10.png)

**Comment by Raruto** [comment]
> where from qplotly plugin initConfig property G3W-CLIENT takes the title value for Charts Plots section

@wlorenzetti `plot.label` and `plot.type` are parsed and displayed at the following lines:

- [g3w-client-plugin-qplotly/service.js#L80-L81](https://github.com/g3w-suite/g3w-client-plugin-qplotly/blob/3aafb22b4f56d27db83a15354134bfc9cc67bb0e/service.js#L80-L81)

- [g3w-client-plugin-qplotly/components/sidebar/multiplot.html#L5-L6](https://github.com/g3w-suite/g3w-client-plugin-qplotly/blob/3aafb22b4f56d27db83a15354134bfc9cc67bb0e/components/sidebar/multiplot.html#L5-L6)

> ![Screenshot_20221010_093426](https://user-images.githubusercontent.com/196809/194817759-bb2fc0f6-2708-483f-b009-64f2ad0a8e6e.png)

As per the `initConfig`, the following should be the full path for the first chart element:

```js
initConfig.group.plugins.qplotly.plots[0].plot.layout.title
```

---

> and for showing chart area?

`chart.title` get parsed and displayed in here:

- [g3w-client-plugin-qplotly/components/content/plotheader.vue#L4](https://github.com/g3w-suite/g3w-client-plugin-qplotly/blob/3aafb22b4f56d27db83a15354134bfc9cc67bb0e/components/content/plotheader.vue#L4)
- [g3w-client-plugin-qplotly/components/content/qplotly.vue#L8-L11](https://github.com/g3w-suite/g3w-client-plugin-qplotly/blob/3aafb22b4f56d27db83a15354134bfc9cc67bb0e/components/content/qplotly.vue#L8-L11)
- [g3w-client-plugin-qplotly/components/content/qplotly.vue#L242-L249](https://github.com/g3w-suite/g3w-client-plugin-qplotly/blob/3aafb22b4f56d27db83a15354134bfc9cc67bb0e/components/content/qplotly.vue#L242-L249)
- [g3w-client-plugin-qplotly/service.js#L496-L497](https://github.com/g3w-suite/g3w-client-plugin-qplotly/blob/3aafb22b4f56d27db83a15354134bfc9cc67bb0e/service.js#L496-L497)

![Screenshot_20221010_093433](https://user-images.githubusercontent.com/196809/194817928-b7aa1f8c-99cd-46bf-a762-59b0d75e9b10.png)

In this case, a call to the rest api is made to receive that value:

- eg. https://dev.g3wsuite.it/qplotly/api/trace/97/buildings_2f43dc1d_6725_42d2_a09b_dd446220104a/149

Testing that URL on **g3w-admin@3.5.dev-20221025135455**, you should get the following result:

```http


GET /qplotly/api/trace/97/buildings_2f43dc1d_6725_42d2_a09b_dd446220104a/149/

HTTP 200 OK
Allow: GET, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

{
    "result": true,
    "data": [
        {
            "labels": [
                "Residential",
                "Residential",
                "Commercial",
                "Residential",
                "Administrative",
                "Commercial",
                "Administrative",
                "Residential",
                "Residential",
                "Administrative",
                "Residential",
                "Commercial",
                "Administrative",
                "Residential",
                "Residential",
                "Administrative",
                "Residential",
                "Commercial",
                "Residential",
                "Commercial"
            ],
            "marker": {
                "colors": [
                    "#00ffff",
                    "#00ffff",
                    "#9acd32",
                    "#00ffff",
                    "#cd5c5c",
                    "#9acd32",
                    "#cd5c5c",
                    "#00ffff",
                    "#00ffff",
                    "#cd5c5c",
                    "#00ffff",
                    "#9acd32",
                    "#cd5c5c",
                    "#00ffff",
                    "#00ffff",
                    "#cd5c5c",
                    "#00ffff",
                    "#9acd32",
                    "#00ffff",
                    "#9acd32"
                ]
            },
            "name": "type",
            "values": [
                20.0,
                20.0,
                20.0,
                20.0,
                20.0,
                20.0,
                20.0,
                20.0,
                20.0,
                20.0,
                20.0,
                20.0,
                20.0,
                20.0,
                20.0,
                20.0,
                20.0,
                20.0,
                20.0,
                20.0
            ],
            "type": "pie"
        }
    ]
}
```

**Comment by Raruto** [comment]
@volterra79 be careful https://github.com/g3w-suite/g3w-client-plugin-qplotly/commit/e5aca50e0d0d88f6d4135db162f81c0089df3e97 it's a pretty breaking change (not at all backwards compatible with previous versions of g3w-admin, ie. **< 3.5-dev** ...)

**Comment by volterra79** [comment]
@Raruto updated in commit https://github.com/g3w-suite/g3w-client-plugin-qplotly/commit/624e1d52be4e92366fc140dcc1045cc5a448f79c

**Comment by wlorenzetti** [comment]
@Raruto @volterra79 this bug is fixed?

**Comment by volterra79** [comment]
@wlorenzetti fixed
