### ISSUE TITLE
Add how to develop section within `README.md`

### ISSUE THREAD

**Issue by Raruto** [g3w-suite/g3w-admin#380]
As per **v3.4** project's [README.md](https://github.com/g3w-suite/g3w-admin/blob/19bdc08d97fbe21e14984ae8b3eb472567211a30/README.md) there is no clear indication that can help third-party developers contribute to **g3w-admin** repository.

**NB** furthermore, files that no longer exist are referenced in the latter file (g3w-admin > [README.md](https://github.com/g3w-suite/g3w-admin/blob/19bdc08d97fbe21e14984ae8b3eb472567211a30/README.md#continuous-integration-testing)).

---

### g3w-admin > ci_scripts > [README.md](https://github.com/g3w-suite/g3w-admin/blob/19bdc08d97fbe21e14984ae8b3eb472567211a30/ci_scripts/README.md#for-local-development)

---

> Build the image for development with dockerfile based on main Ubuntu server images.
> 
> ```
> docker build -f Dockerfile.local-develpment-ubuntu-2004.dockerfile -t g3wsuite/g3w-suite-local-development:20.04 .
> ```
>
> create a `.env` file with main env variable like this:
>
> ```bash
> # absolute path to g3w-admin code
> G3W_SUITE_CODE_PATH=/home/walter/PycharmProjects/g3w_suite_qgis_api
> # absolute path to a plce where mount permanent virtualenv data
> G3W_SUITE_VENV_PATH=/home/envs/g3w-suite-local-dev-docker
> # absolute path to folder contains static and media django folder
> G3W_SUITE_WWW_PATH=/home/www
> ```
>
> set your `local_settings.py` to work inside docker container then run `run_env_development.sh`
>
> ```bash
> ./run_env_development.sh
> ```
>
> a docker container with name `g3w-suite-local-dev` is created, access to container to run django/g3w-suite command. 

---

### g3w-suite-docker > [README_DEV.md](https://github.com/g3w-suite/g3w-suite-docker/blob/e435dcc3eebdace8eec161d34f1426ce20f143bb/README_DEV.md)

---

> Follow instructions are for development environment.
> 
> 1. Copy `.env.example` file into `.env` and edit it: 
>   * set `WEBGIS_DOCKER_SHARED_VOLUME` to a specific folder for permanent volume data;
>   * set `G3WSUITE_DEBUG` to `True`;
>   * set `G3WSUITE_LOCAL_CODE_PATH` with path to your local G3W-SUITE code location.
>
> 2. Run `docker compose -f docker-compose-dev.yml up -d`.
>   1. If all went well G3W-SUITE is running in development mode on http://127.0.0.1:8000

---

### g3w-admin > [README.md](https://github.com/g3w-suite/g3w-admin/blob/19bdc08d97fbe21e14984ae8b3eb472567211a30/README.md#continuous-integration-testing)

---

> The Docker compose configuration used in the CI tests is available at [docker-compose.yml](https://github.com/g3w-suite/g3w-admin/blob/dev/docker-compose.yml).
>
> Another configuration for running local tests is provided with [docker-compose-local.yml](https://github.com/g3w-suite/g3w-admin/blob/dev/docker-compose.yml)
 and can also be used for local testing by running:
>
> ```bash
> docker-compose -f docker-compose-local.yml up
> ```
>
> The testing image is built from the dependency image and it will run all install and build steps from the local repository.
>
> The dependency image is built from the [Dockerfile.deps](https://github.com/g3w-suite/g3w-admin/blob/dev/ci_scripts/Dockerfile).

**Comment by wlorenzetti** [comment]
Local development delegated to the g3w-suite-docker repository: https://github.com/g3w-suite/g3w-admin/commit/01fb111707bcf82cd2ca2e0ccb4c371dd5c62627
