### ISSUE TITLE
Alphanumeric table editing form

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-admin#381]
When inserting a new records on an alphanumeric table, the labels of the fields inside the form appear badly formatted.

This does not happen with the creation of a new feature on geographic layers.

https://v34.g3wsuite.it/it/map/g3w-suite-demo/qdjango/97/

![immagine](https://user-images.githubusercontent.com/4012899/190846748-8419953e-508a-40ee-8ca0-85910450cbb0.png)

**Comment by volterra79** [comment]
@leolami a solution is to put label above input as follow image:
![Screenshot from 2022-09-21 10-51-04](https://user-images.githubusercontent.com/1051694/191465380-1ae166c4-1cbe-4ef9-acef-7a85d3454cbc.png)

**Comment by leolami** [comment]
It seems to me an excellent solution

I would proceed

However, let's consider that on the QGIS project to define the position of labels:
- sideways (as before)
- above (as per your proposal)

However I would proceed in this way and then I would try to manage the thing based on the project settings

**Comment by wlorenzetti** [comment]
Close with https://github.com/g3w-suite/g3w-client/pull/201
