### ISSUE TITLE
1: N relation editing

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-admin#382]
When I try to edit an already existing records inside a 1: N related table, the editing buttons don't work

https://v34.g3wsuite.it/it/map/g3w-suite-demo/qdjango/97/

![immagine](https://user-images.githubusercontent.com/4012899/190846901-f41a4473-3148-4f99-a425-15ef1f4cda71.png)

**Comment by volterra79** [comment]
@leolami corretto

**Comment by wlorenzetti** [comment]
@volterra79 can you write here link to G3W-CLIENT PR that resolve this issue?

**Comment by volterra79** [comment]
@wlorenzetti https://github.com/g3w-suite/g3w-client-plugin-editing/commit/636de47b79329f703c22a8d7d882cd2e0beafeb9

**Comment by wlorenzetti** [comment]
@volterra79 `dev` is just fixed?

**Comment by volterra79** [comment]
@wlorenzetti sure. It was an issue related to 3.4.x
