### ISSUE TITLE
Documenting adding a basemap from local server or other XYZ providers

### ISSUE THREAD

**Issue by NyakudyaA** [g3w-suite/g3w-admin#40]
# Problem
In the Django Admin page you can add base maps but the format is not very clear of how to do it.

Example of OSM
![osm](https://user-images.githubusercontent.com/2510900/74162645-c0c92800-4c29-11ea-8642-a78c47fb68a9.png)

Where is the `servertype` defined in the admin? If I need to add a custom base map coming from my server ie GeoServer, MapServer how to define this.

**Comment by wlorenzetti** [comment]
Hi @Nyakudya, sorry for late in reply, I don't known how it happened,  but a I forget to reply :(.
`servertype` property is not a g3w-admin property, but a OL layer property. 
So what you see into *Property* field is a OL layer object properties.

Servicetype available values are:
- OSM
- TMS
- Bing
- WMTSLayer

This is an example for  a TMS service:
```
{
 "crs": 32632,
 "url": "https://sit.parco.gran-paradiso.g3wsuite.it/caching/api/qdjango34/{z}/{x}/{y}.png",
 "servertype": "TMS",
 "attributions": "<a href='http://metadati.partout.it/metadata_documents/open_data_ctr.pdf' target='_blank'>Regione Autonoma Valle Aosta</a>"
}
```
