### ISSUE TITLE
On create of a new project every from project fields are not saved.

### ISSUE THREAD

**Issue by wlorenzetti** [g3w-suite/g3w-admin#403]
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-admin/issues) and this bug has never been reported before

### Subject of the issue

Not every fields are saved on creation of new project.
I.e. the follow list of fields:

- Public title
- every fields into 'Options and actions' 

### Steps to reproduce

1. On G3W-ADMIN interface got to projects list of a map group.
2. Create a newone and add i.e. aa _Public title_.
3. Got to editing mode of the project form and check _Public title_ input form is empty.

### Environment

- g3w-admin: 3.5.dev-20221027

**Comment by Raruto** [comment]
@wlorenzetti I edited your report by inserting the current version of **g3w-admin** (ie. including at least the current date "**3.5.dev-20221027**" and not just "**dev**"). I know it can be a hassle to specify that information all the time, but without that the bug report becomes useless pretty quickly...

**Comment by wlorenzetti** [comment]
@Raruto  ok thanks, It sound good. After the 3.5 release we need to look together at g3w-admin version management, as we did for g3w-client.

**Comment by Raruto** [comment]
> After the 3.5 release ...

Ok, before that, just when you have a moment remember to check at least this pull: https://github.com/g3w-suite/g3w-suite-docker/pull/62

Without that change on the client we are quite stuck and we could not release a more "stable" version that could be included in the final release of the g3w-admin@v3.5 release. (as right now we are are still at [alpha](https://github.com/g3w-suite/g3w-client/releases/tag/v3.7.0-alpha.1) stage and it would be nice to get the **[g3w-client@v3.7.0-beta](https://github.com/g3w-suite/g3w-client/releases/)** some time before going into production...)
