### ISSUE TITLE
Cannot open a directory where there's a corrupted image (filemanager)

### ISSUE THREAD

**Issue by tudorbarascu** [g3w-suite/g3w-admin#408]
### Checklist

- [x] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-admin/issues) and this bug has never been reported before

### Subject of the issue

The filemanager cannot enter a directory where there's a broken image
```
cannot identify image file '/shared-volume/project_data/user_media/qdjango/f2f20318519d2cc928a1a600e467d998/JPEG_20220926_153525_4520218124612972135.jpg' g3w-suite-1  | DEBUG:g3wadmin.debug:cannot identify image file '/shared-volume/project_data/user_media/qdjango/f2f20318519d2cc928a1a600e467d998/JPEG_20220926_153525_4520218124612972135.jpg'
```

### Steps to reproduce

1. add a 0 bytes jpg file to user_media directory
2. go to that user_media directory with the file manager
3. you cannot see any file although only one is broken

Workaround is currently to delete the broken images.

### Environment

- g3w-admin: __3.5-dev20221002__
- browser: __Firefox / Chrome / Safari__
- operating system: __Windows / Mac Os / Linux (amd64 and Arm)__

**Comment by Raruto** [comment]
Hi @tudorbarascu,

thanks for the report, please to facilitate the work of those who will come later also add some information about the version in which you encountered the problem (eg. g3w-admin@v3.5-dev20221002, Firefox Desktop v106, ...)

> g3w-admin: version
> browser: name
> operating system: name and version (desktop or mobile)

Be aware that every time you report a bug it may take some time before it is carefully evaluated by someone (and this extra step is also to make it easier them work in an attempt to find a solution).

_Have a nice day,
Raruto_

**Comment by tudorbarascu** [comment]
@Raruto Indeed, I first thought of doing so but I think this is a problem for all versions. I'm always using latest so the commit is https://github.com/g3w-suite/g3w-admin/commit/f3d9741a9b63c8601f8677985495f34f96319e89.

The problem is not browser related, it's file-manager/django related.

Thank you

**Comment by Raruto** [comment]
Hi @tudorbarascu,

I hope you forgive me for my fussiness:

> but I think this is a problem for all versions.

Maybe you are right, but please always try to provide that information (even if it may seem useless, looking for a version number among old commits is not the best for research and debugging purposes ..)

> The problem is not browser related, it's file-manager/django related.

Ok, but keep in mind that information is also useful for developers to evaluate more quickly in which environment the problem has already been tested (just in case the problem was not due only to what you think, that is to some bugs exclusively on the server side..)

_Thanks for your cooperation,
Raruto_

**Comment by tudorbarascu** [comment]
Good morning.  The problem can be replicated on Windows on Firefox/Chrome and on MacOs Safari/Firefox/Chrome and on Linux amd64 and Arm using Firefox 106.0.4 (64-bit) and Chromium. Basically, every browser has it.
Than you!
