### ISSUE TITLE
Error printing XYZ tiles

### ISSUE THREAD

**Issue by NyakudyaA** [g3w-suite/g3w-admin#41]
# Problem

I have set up and instance and set up a single XYZ instance of a layer in a project.

I can preview the layer in the viewer
![sample-view](https://user-images.githubusercontent.com/2510900/74165408-bb6ddc80-4c2d-11ea-8266-650e7787bde8.png)

But printing the layer as pdf produces erroneous results.
![prinitng](https://user-images.githubusercontent.com/2510900/74165485-d80a1480-4c2d-11ea-932f-ac36808992ec.png)

I can see the get map request for printing which looks fine:

```url
/ows/1/qdjango/1/?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetPrint&TEMPLATE=map&DPI=150&FORMAT=pdf&CRS=EPSG%3A3857&LAYERS=NGI&map0%3ASCALE=250000&map0%3AEXTENT=2530898.381653669%2C-3657809.155450398%2C2603375.381653669%2C-3607816.2071542763&map0%3AROTATION=0
```

NB: The project is set up with https://github.com/g3w-suite/g3w-suite-docker

Attached sample project 
[qgis-project.zip](https://github.com/g3w-suite/g3w-admin/files/4181737/qgis-project.zip)

**Comment by wlorenzetti** [comment]
@NyakudyaA sorry for delayed response. I just try whit current `dev` version and  is working:
![Schermata da 2020-10-09 10-20-53](https://user-images.githubusercontent.com/196809/95560356-764ab600-0a19-11eb-8a81-7356a25373f9.png)

**Comment by wlorenzetti** [comment]
Try to use current `dev` branch

**Comment by NyakudyaA** [comment]
> Try to use current `dev` branch

Thanks, I will try and revert here

**Comment by Raruto** [comment]
@NyakudyaA It's been a while, can I close this?

**Comment by NyakudyaA** [comment]
I will try to deploy the latest version and test

**Comment by Raruto** [comment]
I'm closing here due to inactivity, feel free to open a new pull request with additional details if you're still experiencing some troubles.

👋 Raruto
