### ISSUE TITLE
Improve user interface for loading projects

### ISSUE THREAD

**Issue by NyakudyaA** [g3w-suite/g3w-admin#42]
# Problem

The UI allows for uploading projects. This will work fine if the project consists of OWS layers and XYZ layers. In instances where your QGIS project consist of data coming from geopackage, shapefiles, etc the server checks if the layers already exist. If not then the upload fails

![projects-load](https://user-images.githubusercontent.com/2510900/74169003-47363780-4c33-11ea-931e-0e28cd4be229.png)

# Solution

* enable upload of zipped data ( which will unzip on the server and store the data and QGIS project to their respective paths)
* This issue will also lead to a lot of headaches in terms of users uploading big data layers ie nginx timeouts as experienced by Geonode. 
* Add a management command that allows publishing a QGIS project and it's associate data

**Comment by wlorenzetti** [comment]
Hi @NyakudyaA I thinked about it serveral times in the past. 
At the moment I publish a new module g3w-suite repository to load 'fisical' data on the server: https://github.com/g3w-suite/g3w-admin-filemanager. 
By this module you can load shape files, rasters and other 'fisical' formats.
I set this issue as 'enhancement'.
Thanks
