### ISSUE TITLE
How to set a custom `G3WSUITE_LOGIN_LOGO` URL?

### ISSUE THREAD

**Issue by bard0x** [g3w-suite/g3w-admin#432]
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-admin/issues) and this bug has never been reported before

### Subject of the issue

I would like to understand how to act in order to go, for example, to replace the logo and for example use my custom css in G3W.

From the documentation I have seen that there are several properties that should draw on this request, for example by setting the `G3WSUITE_LOGIN_LOGO` property in the settings_docker.py and then defining the path of the new logo.

However, I can't understand why if I define a path that can be for example `G3WSUITE_LOGIN_LOGO = '../logo.png'`, this then is not found by the server, giving me a 404 error despite physically present in the server in that specific path.

I also noticed that by default everything belongs to a `'static'` folder which, however, apparently is recreated every time when you stop and restart the containers, so anything inserted in that folder is lost on the next restart.

Could I have info about it?

Thank you

### Environment

- g3w-admin: 3.5-dev
- operating system: Ubuntu Server 20

**Comment by Raruto** [comment]
Hi @bardoz

Please, first update the content of your report according to these indications:

1. in this bug tracker the language to use is **English**, adapt to this standard if you are looking for help from other users
2. if you are looking for help you must always provide the most specific information related to your environment (`dev` version is not a useful information for those who read your reports), in this other issue I have already pointed out how you can do it: https://github.com/g3w-suite/g3w-admin/issues/428#issuecomment-1361478910

In case you don't know how to do it, see the image below to understand how to update the content of a previously sent message:

![img](https://user-images.githubusercontent.com/9614886/209307775-973b408a-a614-40e2-920c-da831ee14ec3.png)

After that let us know, and everyone will be happy to answer you 🥳 

_Greetings,
Raruto_

**Comment by wlorenzetti** [comment]
@bard0x you can customize the layout using css, indicating your own for example the `custom.css` file.

To do this it is necessary to specify at the level of `local_settings.py` to set some constants in particular the following ones (https://g3w-suite.readthedocs.io/en/latest/settings.html#general-layout-settings):

```env
G3WSUITE_CUSTOM_STATIC_URL
G3WSUITE_FAVICON
G3WSUITE_MAIN_LOGO
G3WSUITE_RID_LOGO
G3WSUITE_LOGIN_LOGO
G3WSUITE_CUSTOM_CSS
```

Here is a configuration example:

```py
# Custom settings
# ===========================================
G3WSUITE_CUSTOM_TITLE = 'Municipality of Goofy'

#CLIENT AND ADMIN LAYOUT SETTINGS
# ======================================

G3WSUITE_CUSTOM_STATIC_URL = '/custom_static/'

G3WSUITE_FAVICON = G3WSUITE_CUSTOM_STATIC_URL + 'img/favicon.ico'
G3WSUITE_MAIN_LOGO = G3WSUITE_CUSTOM_STATIC_URL + 'img/g3wsuite_logo.png'
G3WSUITE_RID_LOGO = G3WSUITE_CUSTOM_STATIC_URL + 'img/g3wsuite_logo_rid.png'
G3WSUITE_LOGIN_LOGO = G3WSUITE_CUSTOM_STATIC_URL + 'img/g3wsuite_logo_h48.png'
G3WSUITE_CUSTOM_CSS = [
      G3WSUITE_CUSTOM_STATIC_URL + 'css/custom.css'
]
```

To make this configuration work you need to add one more statement in the Nginx configuration files which will indicate where `/custom_static/` should point to:

```nginx
location /custom_static/ {
    root /shared-volume/project_data/;
}
```
In this case it will point to the same folder as the `project_data` reachable via the filemanager

As configured, you need to move the favicon and other logos into the folder where the custom static will point to.

I hope I have been clear enough :)
