### ISSUE TITLE
Strictly dependent checkbox always checked on search input widget that has a field dependance

### ISSUE THREAD

**Issue by volterra79** [g3w-suite/g3w-admin#439]
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-admin/issues) and this bug has never been reported before

### Subject of the issue

If you have on search widget an input the depend on other input, Strictly dependent checkbox is always checked

Note: Strictly dependent is not translated. Always in English

### Steps to reproduce

1. Create a search widget
2. Add 2 input, where the second one depend on the first one as follow image:
![Screenshot from 2023-01-05 12-18-01](https://user-images.githubusercontent.com/1051694/210768209-da22d972-c150-461d-ac49-1e0d78ff1b11.png)
3. Save it.
4. Edit the search widget already created
![Screenshot from 2023-01-05 12-20-22](https://user-images.githubusercontent.com/1051694/210768456-da630e70-137f-486f-a9d2-2f639839a061.png)

### Environment

- g3w-admin: 3.5, dev
- browser: all

**Comment by wlorenzetti** [comment]
@volterra79 check and close the issue. Thanks.

**Comment by volterra79** [comment]
@wlorenzetti it works. I close it. Thanks
