### ISSUE TITLE
'XMLSyntaxError' object has no attribute 'message'

### ISSUE THREAD

**Issue by scottmug** [g3w-suite/g3w-admin#44]
Hi,
I've tried a number of qgis project files and all uploads get 'XMLSyntaxError' object has no attribute 'message' error message.  I am using gw3admin from repo (not Docker).  
All other facets work as expected.
Thanks in advance, Scott.

**Comment by wlorenzetti** [comment]
Hi @scottmug are you using 'dev' branch and qgis-server 3.4?

**Comment by scottmug** [comment]
Yes, I am 'dev' branch and qgis-server 3.4.

**Comment by wlorenzetti** [comment]
Can you upload a image with 'error' message and a qgis project test?

**Comment by scottmug** [comment]
Hi,
Screenshot is below and file attached.
Error occurs regardless of file used.
Thanks,
Scott

![g3w-admin](https://user-images.githubusercontent.com/9640294/74245435-ab1c3700-4ceb-11ea-9a83-3e4368db889d.png)

[other.zip](https://github.com/g3w-suite/g3w-admin/files/4186193/other.zip)

**Comment by wlorenzetti** [comment]
@scottmug it's strange, I tried to upload your project on my suite and all work correct.
![Schermata del 2020-02-11 15-42-50](https://user-images.githubusercontent.com/196809/74246790-5c6b9e80-4ce5-11ea-9176-4aeeb0aa09a8.png)

Did you follow README instrusctions to deploy G3W-SUITE?

**Comment by scottmug** [comment]
It doesn't work for me, I get the error mentioned.
I made a new file with just a single WMS layer and no background. I was able to get that pas the errors on page, but now it lands on error below.
Is admin using Python3 or is that still in progress?
`

Request Method: | POST
-- | --
http://127.0.0.1/en/admin/qdjango/3857/project/add/
1.11.18
NameError
name 'unicode' is not defined
/opt/g3wsuite/g3w-admin/g3w-admin/qdjango/models.py in get_project_file_path, line 25
/usr/bin/uwsgi-core
3.6.9
['/opt/g3wsuite/g3w-admin/g3w-admin/',  '.',  '',  '/opt/g3wsuite/.venv/lib/python36.zip',  '/opt/g3wsuite/.venv/lib/python3.6',  '/opt/g3wsuite/.venv/lib/python3.6/lib-dynload',  '/usr/lib/python3.6',  '/opt/g3wsuite/.venv/lib/python3.6/site-packages',  '/usr/local/lib/python3.6/dist-packages',  '/usr/lib/python3/dist-packages',  '/opt/g3wsuite/g3w-admin/g3w-admin']
Tue, 11 Feb 2020 14:48:48 +0000

`

**Comment by wlorenzetti** [comment]
It's strange, if you are usign 'dev' branch your installation should be contain Django 2.2.9 not Django 1.11.18 as I can see above.

**Comment by scottmug** [comment]
Oh, my.  It looks like I messed something up here.  Ill pull it again and reinstall.  Thanks for looking.
