### ISSUE TITLE
Add QGIS project bookmarks to API REST `api/config/` 

### ISSUE THREAD

**Issue by wlorenzetti** [g3w-suite/g3w-admin#449]
### Checklist

- [X] I've searched through the [current issues](https://github.com/g3w-suite/g3w-admin/issues) to make sure this feature hasn't been requested already.

### Motivation

In QGIS desktop is possible set geo-bookmarks and save it inside the project:

![Screenshot_20230207_083707](https://user-images.githubusercontent.com/196809/217205214-d089e0b1-a568-4219-a541-8a61deb38818.png)

the feature is port this bookmarks available inside the client `apit/config` API REST.

### Suggested solution

Create a new sections inside the response of `api/config` called `bookmarks` at level of general project informations. 
At level root of API add a `bookmarks` section like this:

```json
...

"bookmarks":[
   {
      "name":"GBook1",
      "nodes":[
         {
            "name":"Book1",
            "exent":[
               1727644.7706999999936670,
               4856430.9479999998584390,
               1728651.4597000000067055,
               4857251.2131000002846122
            ],
            "id":"{aaf00e73-f583-45d1-a08e-0ea681da495e}",
            "crs":{
               "epsg":3003
            }
         }
      ]
   },

  ...

  {
            "name":"Book2",
            "exent":[
               1727644.7706999999936670,
               4856430.9479999998584390,
               1728651.4597000000067055,
               4857251.2131000002846122
            ],
            "id":"{aaf00e73-f583-45d1-a08e-0easadasas495e}",
            "crs":{
               "epsg":3003
            }
         }

]
```

**Comment by volterra79** [comment]
@wlorenzetti in case of bookmark group could be useful add `"expanded":"true/false"` attribute as follow:

```js
"bookmarks": [
  {
    "name":"GBook1",
    "expanded": true,
    "nodes": [ .... ]
  },
```
