### ISSUE TITLE
[CSRF Token] - CSRF SameSite = None

### ISSUE THREAD

**Issue by bard0x** [g3w-suite/g3w-admin#461]
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-admin/issues) and this bug has never been reported before

### Subject of the issue

Hi,

I need to do a login from an iframe that embed G3W.
If I try to login into the application the browser show me this error:

![image](https://user-images.githubusercontent.com/24570908/220557345-426fa73f-9cc5-4fb2-8d8a-3a5e5ee28b81.png)

So I need to set SESSION_COOKIE_SAMESITE to 'none' but if I try to set this in the configuration file (python) I don't have any updates and I don't be able to set the session cookie samesite to None. It is always LAX.

![image](https://user-images.githubusercontent.com/24570908/220557361-0e69a1b8-183e-415f-b464-e1bcac885104.png)

How to solve it?

Thank's in advance

### Steps to reproduce

Embed G3W into Iframe when G3W is deployed on one server with a specific address (example: 10.5.6.147) and my application with iframe is deployed on another server (example: 10.5.6.179).

I need to set the sameSite property for CSRF token to 'NONE' and not to 'Lax'.

### Environment

g3w-admin: 3.5
g3w-client: 3.7
browser: chrome
operating system: Ubuntu Server

**Comment by bard0x** [comment]
## Update:

I was able to set to None the CSRFTOKEN but I don't know why there is another cookie setted to Lax that block the use of G3W if it is embed into an iframe...

![image](https://user-images.githubusercontent.com/24570908/220607166-b1ea8aee-5f9c-401c-823c-ccf4f535c6ec.png)


Any suggestions?

**Comment by Raruto** [comment]
Hi @bard0x did you manage to find a solution by yourself?

We like open knowledge, so please on closing, provide some insight about your solution that might be useful to someone else (otherwise it's just a boring issue.. 😴)

_Thanks in advance_
👋 Raruto
