### ISSUE TITLE
Client froze when opening attribute table

### ISSUE THREAD

**Issue by albintk** [g3w-suite/g3w-admin#475]
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-admin/issues) and this bug has never been reported before

### Subject of the issue

I configured a non-geographic layer with many widgets:

![image](https://user-images.githubusercontent.com/69245131/224026271-ec1764e9-ed5c-49e8-bf6c-dbc952e0c634.png)

One of the widgets are a relation to a vector layer.

Right clicking on this layer in the client and choosing to open attribute table makes the client freeze:

![image](https://user-images.githubusercontent.com/69245131/224026475-11f04057-848d-4f6e-a078-80832e70e8a5.png)

![image](https://user-images.githubusercontent.com/69245131/224026443-c597c652-a8da-478f-9c42-41b0e874e48b.png)

Other tables with few/no widgets are quick to open. I believe if I reduce the number of widgets, it works.

### Steps to reproduce

1. Create a non geographic table in QGIS with many widgets, amongst them a relation to another layer (not sure if this is a cause)
2. Publish it in a map project, right click on the table and choose Open Attribute Table 
3. Client freezes after some time causing "Page Unresponsive" in google chrome

### Environment

- g3w-admin: 3
- g3w-client: __version__
- browser: Google chrome
- operating system: POP!_OS

I used docker to set up G3W

**Comment by wlorenzetti** [comment]
Hi @albintk Could you provide a dataset and a project?

**Comment by albintk** [comment]
Sure, it would look something like this:

[g3w_github_issue.zip](https://github.com/g3w-suite/g3w-admin/files/10942504/g3w_github_issue.zip)

However, it takes while for the table to open but it didn't crash today, not sure what changed and I tried reproducing the error but I couldn't... Sorry for the incomplete report

**Comment by wlorenzetti** [comment]
@albintk what are the server features? CPU number and RAM available?

**Comment by Raruto** [comment]
> ![image](https://user-images.githubusercontent.com/69245131/224026443-c597c652-a8da-478f-9c42-41b0e874e48b.png)

Just to let know @volterra79, I don't have any reproducible test cases, but sometimes the client application slows down heavily for me too (almost to the point of crashing the entire OS, like as above image).

Indeed, I almost always thought it was something more related to **Firefox** + **BrowserSync** performances (i.e. it happens very often in development on port `3000`) than something related to the production environment (i.e. port `8000`)

**Comment by albintk** [comment]
> @albintk what are the server features? CPU number and RAM available?

I run it locally on my computer with specs as:
![image](https://user-images.githubusercontent.com/69245131/224918647-fbd4e7b6-4dc0-41f6-a02b-867eabfbb875.png)

**Comment by wlorenzetti** [comment]
Hi sorry for delay but I didn't found a cause for this problem. Has the problem still occurred?

**Comment by wlorenzetti** [comment]
@albintk I close this issue, it's been a long time with no news, feel free to reopen it if the error occurs again.

**Comment by albintk** [comment]
Hi Walter,

Sure, and sorry for the long delay in responding and thanks for getting
back. G3W is still very relevant to us so I hope to keep communication and
any posting issues further on.

All the best,
Albin

Den mån 22 maj 2023 08:41Walter Lorenzetti ***@***.***> skrev:
