### ISSUE TITLE
No module named `qtimeseries.apiurls`

### ISSUE THREAD

**Issue by Raruto** [g3w-suite/g3w-admin#489]
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-admin/issues) and this bug has never been reported before

### Subject of the issue

After performing a clean install I've noticed that the following warning is displayed within the docker log:

```
No module named 'qtimeseries.apiurls'
```

### Steps to reproduce

1. follow the installation instructions in here: [g3w-suite-docker/README_DEV.md](https://github.com/g3w-suite/g3w-suite-docker/blob/9475d8260979309e9e583a951306326b016247ea/README_DEV.md)
2. and remember to update `G3WSUITE_LOCAL_CODE_PATH` path accordingly to your local G3W-SUITE code location. 🎗️ 😜

### Environment

- g3w-admin: __v3.5.dev-20230322091536__
- operating system: __Windows 11 (64 bit)__

**Comment by wlorenzetti** [comment]
@Raruto this is a message log, is not a issue.

**Comment by Raruto** [comment]
Surely it's just a nuisance, since it appears several times in the log..

If i remember correctly we should just add an empty file (eg: `qtimeseries/apiurls.py` ) to fix that kind of warnings.
