### ISSUE TITLE
Error Paver start

### ISSUE THREAD

**Issue by dpadron** [g3w-suite/g3w-admin#5]
Hello, the following error occurs when running paver start:

paver start
---> pavement.start
python g3w-admin/manage.py runserver  &
G3W-SUITE is now available.
(g3wsuite) root@videsa:/home/g3w/g3w-admin# Traceback (most recent call last):
  File "g3w-admin/manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management

**Comment by wlorenzetti** [comment]
Hi, 
are you in the virtualenv?

**Comment by dpadron** [comment]
Hello Walter, If I'm in virtualenv. I run again executing paver start. Strange

**Comment by wlorenzetti** [comment]
@dpadron have you again problens?

**Comment by imbucato** [comment]
Hi,
I have similar problem to `paver install`
I'm in virtualenv "g3wsuite" and run `paver install` but this is the result:
`Build failed: Unknown task: install`

**Comment by imbucato** [comment]
Resolved. I restarted the installation from the beginning. I was probabily wrong about something. But I had to run paver install in the `g3w-admin` folder and not in the virtualenv

**Comment by wlorenzetti** [comment]
Good @imbucato , an important thing is to use 'dev' branch.
