### ISSUE TITLE
Upload Error

### ISSUE THREAD

**Issue by abrousseau89** [g3w-suite/g3w-admin#505]
### Checklist

- [X] I've searched through the [current issues](https://github.com/g3w-suite/g3w-admin/issues) to make sure this feature hasn't been requested already.

### Motivation

Hi, 

When I upload a Qgis project I always have the same error messages. 

`Project error on layers()]-- [Layer error on datasource(communes_nantes20201103142300159)]-- : Current datasource is /shared-volume/media/temp_uploads/communes_nantes.shp`

My project is a QGZ format and I use three SHP files.

An idea ? 
Thanks

### Suggested solution

Is it a QGIS file configuration problem?

**Comment by wlorenzetti** [comment]
@abrousseau89 try to follow this documentation page: https://g3w-suite.readthedocs.io/en/latest/datamanagement.html?highlight=project_data

**Comment by abrousseau89** [comment]
Thx,

I work on Windows Qgis. 

I create my main folder on Windows Desktop and a subolder projects, and project_data

In projects, i create my QGZ file

In project_data , i create my geopackage

In Filemanager of G3wSuite i upload my geopackage (straight to the root)

After i add a group and create a new project. 

When i upload my Qgis File, i have an error : 

`datasource(nantes___nantes_communes_cc1fffeb_3afb_49d5_881f_a13169cd0e5b)]-- : Current datasource is /shared-volume/media/nantes.gpkg`

If i show the folder shared-volume/media on my ubuntu server,  I don't see the file nantes.gpkg. But if i show the folder shared-volume/project data on my server, i see the file !!!

So I missed something in the configuration? I have to change a setting so that everything is in the right folders? 

Despite your documentation, I did not understand the process

Thanks

**Comment by wlorenzetti** [comment]
Could you upload here your QGIS project?

**Comment by abrousseau89** [comment]
Yes, you can download here : 

https://formationsig-greta.fr/productions/academies-20160209-shp.zip

**Comment by wlorenzetti** [comment]
@abrousseau89 I check your project and data and the relations are not correct.
Infact if I try to open the project from QGIS desktop I obtain the following error:

![Screenshot_20230329_091442](https://user-images.githubusercontent.com/196809/228455994-fc807641-0288-4836-ba41-a26e2cdddd4a.png)
![Screenshot_20230329_091505](https://user-images.githubusercontent.com/196809/228456019-2d81b23e-e4aa-412a-a1a3-6d57c5135172.png)
QGIS can not load a layer (`nantes-communes`) because the position's dat ainsede the qgs project is no correct:

```xml
...
<id>nantes___nantes_communes_cc1fffeb_3afb_49d5_881f_a13169cd0e5b</id>
      <datasource>../nantes.gpkg</datasource>
...
```

Try to fix it and try to upload again in G3W-SUITE

**Comment by abrousseau89** [comment]
Great ! 

Thanks a lot for your help.

I make basic stupid mistakes...

I will now be able to use G3WSuite.

I plan to propose it to my students for my teaching on WebGIS and Qgis. Is there no problem with that?

![image](https://user-images.githubusercontent.com/127750775/228459855-58b0e015-0802-463e-966c-f74cec889594.png)

**Comment by wlorenzetti** [comment]
Sure @abrousseau89 please send us some pictures about the course! Thanks.
