### ISSUE TITLE
Page loading indicator stuck at 99% (Firefox browser)

### ISSUE THREAD

**Issue by Raruto** [g3w-suite/g3w-admin#507]
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-admin/issues) and this bug has never been reported before

### Subject of the issue

The JS code related to the progress bar doesn't seem to work correctly on Firefox browser (ie. it seems to never listen for the "page loaded" event).

### Steps to reproduce

1. get a Firefox browser
2. visit any admin page to get the following situation:

![image](https://user-images.githubusercontent.com/9614886/228233504-9dfa0411-24c6-489f-b0ce-7cb1fa4789b1.png)

### Environment

- g3w-admin: __3.5.dev-20230328083602__
- g3w-client: __3.8.0-alpha.2__
- browser: __Firefox 111.0__
- operating system: __Windows 11 64-bit__

**Comment by wlorenzetti** [comment]
I can't recreate it. Can you see on console log if there is a js library, font or other static feature that is not loaded correctly?

**Comment by Raruto** [comment]
Here you can find the HAR file: [localhost [23-03-28 15-17-01].zip](https://github.com/g3w-suite/g3w-admin/files/11089888/localhost.23-03-28.15-17-01.zip)


![image](https://user-images.githubusercontent.com/9614886/228250792-696e32e8-15c8-4b69-962f-ccdb840c4695.png)

I didn't check if it could be an ad-blocker issue or some other browser related setting.

**Comment by abrousseau89** [comment]
Hi, 

It's much longer in Firefox. It takes a moment on 99% before it disappears. In Chrome it is very fast. Same in Edge. I think it's the translations.

![image](https://user-images.githubusercontent.com/127750775/228855160-6ca4aac7-ec1d-4181-b141-cb3610dffcc2.png)

**Comment by wlorenzetti** [comment]
@abrousseau89 we are looking on this issue, this seems to happen in the current development version, I suggest you use the latest stable version v3.5.x: https://github.com/g3w-suite/g3w-suite-docker/tree/v3.5.x

**Comment by Raruto** [comment]
> this seems to happen in the current development version,

@wlorenzetti Although, I think this problem has always been there (or at least that's what I remember since my first tries with **v3.4**)

> It's much longer in Firefox. It takes a moment on 99% before it disappears. In Chrome it is very fast. Same in Edge. I think it's the translations.

@abrousseau89 I never did a deep analysis, but it never seemed to me that there were particularly slow downloading files. Most of the time it seems that the indicator is hidden due to the expiration of JS timer (inside the JS library) rather than after completing downloading of some specific assets.

Anyway, if you have any more information about it, let us know (eg. do you have problems even reloading it without browser extensions? since you're talking about translations, are you referring to any file or URL in particular? ...)

👋 Raruto

**Comment by wlorenzetti** [comment]
@Raruto it seams related to Firefox on Windows, here possible solutions: https://www.positioniseverything.net/ns_binding_aborted/

**Comment by Raruto** [comment]
@abrousseau89 Are you able to tell us if you encounter this problematic also in a production environment?

**Comment by abrousseau89** [comment]
@Raruto Yes same. I test to update pace.js library with no effect.

I don't have any browser extensions on Firefox. I juste see in Firefox network 

I just saw that in Firefox Network, several files take longer to load (see screenshot above). Could this be a lead?

**Comment by Raruto** [comment]
> it seams related to Firefox on Windows

It's a long standing issue related to `pace.js` on "ready state" page detection:

https://github.com/search?q=repo%3ACodeByZach%2Fpace+99%25&type=issues

>  test to update pace.js library with no effect.

@abrousseau89 Do you confirm that it works by applying the following configuration instead? 👉  https://github.com/g3w-suite/g3w-admin/pull/514/commits/e29012052aa98030580e9e111ba8f6781e2db203

👋 Raruto

**Comment by abrousseau89** [comment]
> @abrousseau89 Do you confirm that it works by applying the following configuration instead? 👉 [e290120](https://github.com/g3w-suite/g3w-admin/commit/e29012052aa98030580e9e111ba8f6781e2db203)

@Raruto Yes!

If i replace    

```html
<script src="{% static "bower_components/pace/pace.min.js" %}"></script>
```

by 

```html
<script src="{% static "bower_components/pace/pace.min.js" %}" data-pace-options='{ "eventLag": false }'></script>
```

in `base.html`, it works perfectly 

Really very fast loading and the bar disappears correctly once it reaches 100%

**Tested with:**

- Firefox 112.0.2
- Chrome 112.0.5615.138
- Edge 113.0.1774.35
