### ISSUE TITLE
Query data cross different layers

### ISSUE THREAD

**Issue by bard0x** [g3w-suite/g3w-admin#548]
### Checklist

- [X] I've searched through the [current issues](https://github.com/g3w-suite/g3w-admin/issues) to make sure this feature hasn't been requested already.

### Motivation

Hello everyone,

It is possible to query data cross different layers? Imagine that I want to query the LAYER N°1 and LAYER N°2 that belong to the same id (info contained at both layers).

Thank you in advance for the reply.

Bard0x

### Suggested solution

I don't have any solution to suggest you

**Comment by wlorenzetti** [comment]
Hi @bard0x , at now you can create search widget that query data cross  different layer:

![Screenshot_20230522_082741](https://github.com/g3w-suite/g3w-admin/assets/196809/409880f2-333e-406c-8975-5479f601c6a3)

At the bottom of search widget creation/update form, in this inputbox you'll find layer with the same _datasource_ of the main layer on wich you're creating the searching widget.
