### ISSUE TITLE
Add Macrogroup get an error

### ISSUE THREAD

**Issue by volterra79** [g3w-suite/g3w-admin#565]
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-admin/issues) and this bug has never been reported before

### Subject of the issue

If i try to add new Macrogroup, i receive **Server Error (500)** message

### Steps to reproduce

1. Click on Add MACRO group

![Screenshot from 2023-06-29 16-16-37](https://github.com/g3w-suite/g3w-admin/assets/1051694/15706ca8-e9f2-4a22-8489-fc6355b1da60)

2. Get error
3. 
![Screenshot from 2023-06-29 16-17-23](https://github.com/g3w-suite/g3w-admin/assets/1051694/66399dbd-aace-4489-9558-e432f24f5400)

### Environment

- g3w-admin: 3.6.x

**Comment by wlorenzetti** [comment]
Closed with: https://github.com/g3w-suite/g3w-admin/pull/566
