### ISSUE TITLE
Switching map THEME throws TypeError: Cannot reading properties of undefined

### ISSUE THREAD

**Issue by dotsLand** [g3w-suite/g3w-admin#578]
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-client/issues) and this bug has never been reported before

### Subject of the issue

After I `Choose a theme` in map the following error is shown in console:

![image](https://github.com/g3w-suite/g3w-client/assets/107835719/caf3a6ee-2080-418b-ad84-591c7cf4afaa)

### Steps to reproduce

1. Open the [Statistical aspects](https://dev.g3wsuite.it/en/map/statistic/?map_extent=1007982.1488061137%2C5189697.856848119%2C1558233.6998410644%2C5548938.519148007) map
2. Select a THEME and Error will appear in Console

### Environment

- g3w-admin: __3.6.dev-20230804130717__
- g3w-client: __3.8.6__
- browser: __Chrome 115.0.0.0__
- operating system: __Windows 10 64-bit__

### Link to your project

https://dev.g3wsuite.it/en/map/statistic/

### Additional info

The same error in my local environment:

![image](https://github.com/g3w-suite/g3w-client/assets/107835719/d1f9c13f-25c0-4fe9-ad51-f4035a177332)

**Comment by volterra79** [comment]
@dotsLand i try to follow the steps that you report but no error occurs.

![Screenshot from 2023-08-07 14-14-24](https://github.com/g3w-suite/g3w-client/assets/1051694/9294dbfe-e81b-4bc7-9f9f-a0bb63cfc3a3)


![Screenshot from 2023-08-07 14-14-35](https://github.com/g3w-suite/g3w-client/assets/1051694/25a8bc58-30ec-435b-bdce-9823432eb854)


![Screenshot from 2023-08-07 14-14-50](https://github.com/g3w-suite/g3w-client/assets/1051694/19673fa9-7f55-4746-85b2-f0e83d8f6edc)

**Comment by dotsLand** [comment]
i have check in other browser(Firefox) again same: this is link https://dev.g3wsuite.it/en/map/statistic/


- g3w-admin: __3.6.dev-20230804130717__
- g3w-client: __3.8.6__
- browser: __Firefox 116.0__
- operating system: __Windows 10 64-bit__

**Comment by volterra79** [comment]
@dotsLand replicate in Firefox 113.0.2. I work on it. Thanks

**Comment by Raruto** [comment]
@wlorenzetti Ref: https://github.com/g3w-suite/g3w-admin/pull/579, https://github.com/g3w-suite/g3w-admin/pull/582, https://github.com/g3w-suite/g3w-admin/pull/586

I think you need to target `dev` at first if you want to close this issue.

After that you can **backport** (when feasible) the squashed commit to previous branches, eg: `v3.6.x`.

👋 Raruto
