### ISSUE TITLE
Layer feature with more than one geometry field fail on editing update

### ISSUE THREAD

**Issue by wlorenzetti** [g3w-suite/g3w-admin#613]
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-admin/issues) and this bug has never been reported before

### Subject of the issue

Given a layer with more than one geometric type field (PostGis layer i.e.) 

The PostGis table has a column _geom_ point type and it has another geometry column _geom_pol_ polygon
![Screenshot_20231010_100917](https://github.com/g3w-suite/g3w-admin/assets/196809/9eb07ef3-d26c-468a-b2c7-5dbac6e975e5)

In this case when I try to update a point feature on save I obtain the following error:

```json
{
   "result":false,
   "errors":{
      "double_geom":{
         "update":{
            "id":"8",
            "fields":"Error changing attribute values: PostGIS error while changing attributes: ERROR:  parse error - invalid geometry\n"
         }
      }
   }
}
```

This is the error in the PostgreSQL/PostGis log:
```
[PostGIS] - Erroneous query: UPDATE "g3w_suite"."double_geom" SET "gid"=8,"name"='Test',"geom_pol"=st_geomfromewkt('') WHERE "gid"=8 returned 7 [ERROR:  parse error - invalid geometry
```

### Steps to reproduce

1. Create a layer on PotGis with more than one geometry colum.
2. Publish the project on G3W-SUITE
3. Active editing state for the layer
4. Add newone feature
5. Try to update the feature.

### Environment

- g3w-admin: dev branch
- g3w-client: 3.9.0-alpha.1
- browser: Firefox
- operating system: Ubuntu 22.04

**Comment by Raruto** [comment]
> ## Environment
> - g3w-admin: dev branch

@wlorenzetti you can easily get (copy-paste) more accurate information from browser's console..

![image](https://github.com/g3w-suite/g3w-admin/assets/9614886/21fbb2e4-6c58-4e6e-b47b-9a0fc7c99d59)

```
[g3wsdk.info]

- g3w-admin: __v3.6.11__
- g3w-client: __3.8.10__
- browser: __Firefox 118.0__
- operating system: __Windows 10 64-bit__
``` 

Currently, only OS detection is not very accurate..
