### ISSUE TITLE
:bug: Permission on webgis

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-admin#663]
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-admin/issues) and this bug has never been reported before

### Subject of the issue
Layer ACL server filter fail when a user's restricted layer  (not view) is call inside a GetLegendGraphic and GetMap WMS REQUEST but the same layer is available (grant to view) fro Anonymous user.

![Screenshot_20231120_113402](https://github.com/g3w-suite/g3w-admin/assets/196809/d3597952-83a8-44ba-9124-2565d1a94b0a)

### Steps to reproduce
- Public a project on G3W-SUITE
- Give to Anonymous user access also on every layers of the project
- Add permission to the project  to a Viewer Level 1
- Remove grant view permission on one layer to Viewer Level 1 user
- Open the webgis service as Viewer Level 1

### Environment
- g3w-admin: __3.7.dev-20231120102359__
- g3w-client: __3.9.0-alpha.2.0__
- browser: __Chrome 119.0.0.0__
- operating system: __Linux 64-bit__

### Link to your project

https://dev.g3wsuite.it/it/map/g3w-suite-demo/qdjango/97/

**Comment by wlorenzetti** [comment]
@leolami I just rewrite the issue because the reason for the bug it's just different.

**Comment by leolami** [comment]
I think the problem I highlight is different from Tudor's

I published a project for the AnonymosUser user only and I hide a layer (ANTENNE) for the same AnonymosUser

When accessing that project (as Anonymus) I get the error message reported

https://dev.g3wsuite.it/it/map/test-db/qdjango/19/

**Comment by wlorenzetti** [comment]
@leolami for me work fine:

as admin01 user:

![Screenshot_20231220_114010](https://github.com/g3w-suite/g3w-admin/assets/196809/b7ccecb8-0918-4c72-921f-b0065350e5d9)

as anonymous user:

![Screenshot_20231220_113959](https://github.com/g3w-suite/g3w-admin/assets/196809/8fa99119-1745-4a54-be3b-6eca971123a1)

**Comment by wlorenzetti** [comment]
@leolami I think it was related to this issue: #688 that i just merged
