### ISSUE TITLE
Some layers present in the project are not currently available (Emilia Romagna WMS)

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-admin#664]
### Checklist

- [x] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-admin/issues) and this bug has never been reported before

### Subject of the issue

I have a project with AdE's WMS

Link reported

I try to query and there are no results...

I went to Admin to put WMS external but the checkbox is no longer there....

Otehr problem on this project:

This project has an EmiliaRomagna WMS but it is not shown...
https://dev.g3wsuite.it/it/map/epsg-25832/qdjango/37/

### Steps to reproduce

Try to query the WMS layer

### Environment

- g3w-admin: 3.7 dev
- g3w-client: 3.7 dev
- browser: __name__
- operating system: __name and version (desktop or mobile)__

### Link to your project

https://dev.g3wsuite.it/it/map/g3w-suite-demo/qdjango/235/

**Comment by wlorenzetti** [comment]
@leolami first of all, please don't put many bugs inside a only one issue. 
For https://dev.g3wsuite.it/it/map/g3w-suite-demo/qdjango/235/ and AdE WMS if you don't put WMS external, QGIS server never send you a response on GetFeatureRequest, for to make available a WMS layer insiade a project as external WMS you is necessary that the WMS loaded in the project mus loaded with same EPSG of the map, ion this case AdE is in 25832 but map is in 3857.

**Comment by wlorenzetti** [comment]
@leolami do you checked it? Can I close the issue?

**Comment by leolami** [comment]
This service based on WMS of the Emilia Romagna Region does not yet work
https://dev.g3wsuite.it/it/map/g3w-suite-demo/qdjango/235/

The massage say:
 Some layers present in the project are not currently available and therefore do not appear in the current view

It works on QGIS

**Comment by wlorenzetti** [comment]
@leolami the dev.g3wsuite it was not updated, I just save again the the project and now it seem works fine: https://dev.g3wsuite.it/it/map/g3w-suite-demo/qdjango/235/

**Comment by leolami** [comment]
The EMILIA ROMAGNA WMS layer give the same problem in 3.7 and in dev

https://v37.g3wsuite.it/it/map/epsg-25832/qdjango/37/

https://dev.g3wsuite.it/en/map/epsg-25832/qdjango/37/

**Comment by wlorenzetti** [comment]
@volterra79 we need to check it together

**Comment by Raruto** [comment]
@leolami is this still a thing?

**Comment by leolami** [comment]
Ok, now it works

Thanks
