### ISSUE TITLE
ADMIN LAYER LIST: icon popup

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-admin#665]
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-admin/issues) and this bug has never been reported before

### Subject of the issue

English translation of layer function icons on Admin are incorrect:

 Here the correct translation for the two correspondent icons

- Hide layer
- Hide table fields

### Steps to reproduce

See on the admin list layers

### Environment

- g3w-admin: 3.7 dev
- g3w-client: 3.7 dev
- browser: __name__
- operating system: __name and version (desktop or mobile)__

**Comment by wlorenzetti** [comment]
Fix throw: https://github.com/g3w-suite/g3w-admin/pull/680

**Comment by leolami** [comment]
The italian translation of this icon is not right:

Thr translation must be: 
![immagine](https://github.com/g3w-suite/g3w-admin/assets/4012899/1de9e8c2-0602-4600-8a04-8f4e4e202f35) Nascondi layer per utenti/gruppi
![immagine](https://github.com/g3w-suite/g3w-admin/assets/4012899/c537a8e1-fd0b-43a0-883f-0dfd27afdb1c) Nascondi colonne per utenti/gruppi
