### ISSUE TITLE
Make starting webgis services faster

### ISSUE THREAD

**Issue by wlorenzetti** [g3w-suite/g3w-admin#673]
### Checklist

- [X] I've searched through the [current issues](https://github.com/g3w-suite/g3w-admin/issues) to make sure this feature hasn't been requested already.

### Motivation

When a QGIS project has many layers, the relative webgis service can be very slow.

### Suggested solution

Try to cache the result of /api/config API REST and invalidate it on changing of QGIS project layer or other related features like layers widgets, filters etc.

**Comment by dotsLand** [comment]
That's a very good attempt to cache the configuration. Another beneficial option would be to cache the 'GetLegend' process, as it's taking a considerable amount of time:
![image](https://github.com/g3w-suite/g3w-admin/assets/107835719/d912846f-00be-4171-8d59-d66c550a9900)

**Comment by wlorenzetti** [comment]
Thanks @dotsLand nice request, unfortunately we are now releasing v3.7, I will add it in v3.8
