### ISSUE TITLE
:bug: Map Theme page not found 

### ISSUE THREAD

**Issue by volterra79** [g3w-suite/g3w-admin#677]
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-admin/issues) and this bug has never been reported before

### Subject of the issue

In case of map theme with dot or special character ex. TAV.03 - Carta aree protette, 
request `qdjango/api/prjtheme/50/TAV.03%20-%20Carta%20aree%20protette/` get **Page not found (404)**

### Steps to reproduce

1. Create a Map theme with name TAV.03 - Carta aree protette
![Screenshot from 2023-11-29 11-17-56](https://github.com/g3w-suite/g3w-admin/assets/1051694/e914c4a6-71fc-4a68-8b33-28564a59daa1)

2. Select Map theme on application

![Screenshot from 2023-11-29 11-19-59](https://github.com/g3w-suite/g3w-admin/assets/1051694/28d050b3-ffe0-4f61-ad0d-c679462e2d7f)

### Environment

- g3w-admin: 3.7.dev-20231129095352
- g3w-client: 3.9.0-beta.0
- browser: all

**Comment by volterra79** [comment]
@wlorenzetti the issue is due by **dot** on name of map theme TAV.03

**Comment by wlorenzetti** [comment]
Ok thanks
