### ISSUE TITLE
Vector API count features is not correct

### ISSUE THREAD

**Issue by wlorenzetti** [g3w-suite/g3w-admin#69]
On 'vector' API total count features broken:
I.e. for a url like  **/vector/api/data/qdjango/6/cities_54d40b01_2af8_4b17_8495_c5833485536e/?page=1&page_size=10&ordering=ogc_fid**, the response is:
```json
{
    "result": true,
    "vector": {
        "format": "GeoJSON",
        "pk": "ogc_fid",
        "count": "10",
        "data": {
            "features": [
                {
       ....
```
`count` property is not correct, it must be equal to the total features layer, instead is equal to the `page_size` url param.

**Comment by elpaso** [comment]
This might be tricky or impossible if filters are in place, expecially constraints.

**Comment by elpaso** [comment]
@wlorenzetti the test is probably a little weak (it just tests for not None) but now you get the `featureCount` from the underlying layer in `"count"`

**Comment by elpaso** [comment]
@wlorenzetti it is not clear to me if the expected result reported by `count` is the total unfiltered number of features on the data source or the filtered one (for example by a subset string constraint or by a filter expression or by a search filter).

**Comment by elpaso** [comment]
... forgot BBOX filter of course

**Comment by wlorenzetti** [comment]
I understand pagining system now is a filter, but  for client pagination is necessary to kown total 'filtered' features excluding paging filter.. 
I.e. if  I have 100 filtered features (filtered by filter expression, bbox etc..), and ask page=1&page_size=10 .. client expects count 100...

**Comment by elpaso** [comment]
@wlorenzetti ok, so we need to leave this issue open, because it's not yet resolved and more work and tests are required.

**Comment by elpaso** [comment]
Hopefully fixed by commit https://github.com/g3w-suite/g3w-admin/commit/33e5f36d1952dddab5c5d6508d8a55353fb85adc with new tests too.
