### ISSUE TITLE
Vector API 'page_size' URL param not works.

### ISSUE THREAD

**Issue by wlorenzetti** [g3w-suite/g3w-admin#70]
URL param 'page_size' not works good:
I.e. **/vector/api/data/qdjango/6/countries_4a93c15c_3360_4771_806f_0ba92574ec0e/?page=1&page_size=50&ordering=ogc_fid** with a page_size equal to 50, server reply with a list of only 10 features.

**Comment by elpaso** [comment]
I cannot reproduce this one in the tests. Maybe because I've made some modifications after the other issue #69 .
