### ISSUE TITLE
User filter not saved

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-admin#719]
### Checklist

- [x] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-client/issues) and this bug has never been reported before

### Subject of the issue

The feature filter saved by the user does not reappear when the page is reloaded

So it is not saved

### Steps to reproduce

1. Select features and enable filter
2. Save filter with name
3. Reload map
4. New filter is not on filter list of layer

### Environment

- g3w-admin: 3.7.3
- g3w-client: __version__
- browser: __name__
- operating system: __name and version (desktop or mobile)__

### Link to your project

https://v37.g3wsuite.it/it/map/for_alias/qdjango/97/

**Comment by volterra79** [comment]
@wlorenzetti for exmple if i run this https://v37.g3wsuite.it/vector/api/filtertoken/qdjango/97/buildings_2f43dc1d_6725_42d2_a09b_dd446220104a/?mode=save&name=Fra, i receive a Server Error (500)
