### ISSUE TITLE
Cannot access the WFS3 (OGC API Features) endpoint although WFS is active

### ISSUE THREAD

**Issue by tudorbarascu** [g3w-suite/g3w-admin#722]
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-admin/issues) and this bug has never been reported before

### Subject of the issue

Hello

For a service with normal WFS access, I can access the WMS and WFS services using:

``https://my.domain/ows/test/?service=WFS&REQUEST=GetCapabilities``
``https://my.domain/ows/test/?service=WMS&REQUEST=GetCapabilities``

I tried accessing ``https://my.domain/ows/test/WFS3`` but to no avail. Is the WFS3 endpoint available somewhere, where is the endpoint located?

### Steps to reproduce

1. Setup WFS access in QGIS project
2. Publish service in g3w-suite
3. Try and acess WFS3 endpoint

### Environment

- g3w-admin: __version__
- g3w-client: __version__
- browser: __name__
- operating system: __name and version (desktop or mobile)__

**Comment by Raruto** [comment]
Hi @tudorbarascu,

> ### Environment
>
> - g3w-admin: __version__
> - g3w-client: __version__
> - browser: __name__
> - operating system: __name and version (desktop or mobile)__

please remember, you can get above information from the browser console: `g3wsdk.info()`

> ### Link to your project
>
> _No response_

Not mandatory, but if you have something public, feel free to add a link as it helps a lot in triage
