### ISSUE TITLE
:sparkles: Add the membership macrogroups in the initconfig

### ISSUE THREAD

**Issue by wlorenzetti** [g3w-suite/g3w-admin#760]
### Checklist

- [x] I've searched through the [current issues](https://github.com/g3w-suite/g3w-admin/issues) to make sure this feature hasn't been requested already.

### Motivation

Add the list of macrogroup id memebreship.

### Suggested solution

Add a new property to response of `/api/initconfig` `macrogroup_id` as a list of id, i.e.:

```jsonc
{
...
'group':
  {
  ...
  'macrogroup_id': [2,4,7,9]
  ...
  }
...
}
```

**Comment by Raruto** [comment]
@wlorenzetti @volterra79 you can also use `jsonc` to make it look your json-like snippets nicer:

## Before (`json`)

```json
{
 ...
'group':
  {
  ...
  'macrogroup_id': [2,4,7,9]
  ...
  }
 ...
}
```

## After (`jsonc`)

```jsonc
{
...
'group':
  {
   ...
  'macrogroup_id': [2,4,7,9]
  ...
  }
...
}
```

Ref: [Creating and highlighting code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting)

**Comment by wlorenzetti** [comment]
@Raruto thanks.
