### ISSUE TITLE
Cookie `“g3wclientsessiontoken”` does not have a proper `“SameSite”` attribute value.

### ISSUE THREAD

**Issue by Raruto** [g3w-suite/g3w-admin#791]
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-admin/issues) and this bug has never been reported before

### Subject of the issue

Should be fixed in future releases:

> Cookie “g3wclientsessiontoken” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

### Steps to reproduce

- open any demo project

![image](https://github.com/g3w-suite/g3w-admin/assets/9614886/20933c87-e030-40ed-9535-b3a4941fd5f4)

- analyzes cookie settings

![image](https://github.com/g3w-suite/g3w-admin/assets/9614886/4995e521-f258-4878-a284-3f6dec84f15e)

### Environment

[g3wsdk.info]

- g3w-admin: __v3.7.6__
- g3w-client: __3.9.5__
- browser: __Firefox 124.0__
- operating system: __Windows 10 64-bit__

### Link to your project

https://v37.g3wsuite.it/it/map/demo-37/

**Comment by wlorenzetti** [comment]
@Raruto test now if is it correct.

**Comment by Raruto** [comment]
@wlorenzetti nothing has changed for: https://v37.g3wsuite.it/it/map/demo-37/.

If I remember correctly it had been managed in here somehow: [portal/apps.py#L17-L31](https://github.com/g3w-suite/g3w-admin-portal/blob/47cd966ae089ca16107e79eb242324349ef851bc/portal/apps.py#L17-L31)

BTW, I think it could have greater implications (better not to work for it in 3.7/3.8).

**Comment by Raruto** [comment]
> Cookie “g3wclientsessiontoken” will be soon rejected because it has the “SameSite” attribute set to “None” **without the “secure” attribute.** To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

> Note: A [Secure](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#secure) cookie is only sent to the server with an encrypted request over the HTTPS protocol. Note that **insecure sites (http:) can't set cookies with the Secure directive, and therefore can't use SameSite=None.**

@wlorenzetti ref: https://github.com/g3w-suite/g3w-admin/pull/793
