### ISSUE TITLE
Filter displayed groups

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-admin#808]
### Checklist

- [x] I've searched through the [current issues](../issues) to make sure this feature hasn't been requested already.

### Motivation

In the list of Cartographic Groups it is necessary to be able to filter the Groups based on the MacroGroup they belong to.

### Suggested solution

Once the MacroGroup has been chosen (for example from a drop-down menu), the name of the chosen Macrogroup and only the associated Groups must be reported

Remember that there may be Groups not associated with any MacroGroup

**Comment by leolami** [comment]
Can you add a filter for Editor2 user and Editor2 user groups?

So you can find all the cartographics groups associated to a specific Editor2

If possibile put the new filter on the rigth of the others, like so:

![Image](https://github.com/g3w-suite/g3w-admin/assets/4012899/ad45586b-5965-4d28-9c14-d98992a804e1)

**Comment by leolami** [comment]
Is it possible to show only the EPSG used in the present Cartoghrapic Groups and not all the EPSG?

**Comment by wlorenzetti** [comment]
> Can you add a filter for Editor2 user and Editor2 user groups?
> 
> So you can find all the cartographics groups associated to a specific Editor2
> 
> If possibile put the new filter on the rigth of the others, like so:
> 
> ![Image](https://private-user-images.githubusercontent.com/4012899/332703899-ad45586b-5965-4d28-9c14-d98992a804e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNjM4MzYsIm5iZiI6MTcxNjM2MzUzNiwicGF0aCI6Ii80MDEyODk5LzMzMjcwMzg5OS1hZDQ1NTg2Yi01OTY1LTRkMjgtOWMxNC1kOTg5OTJhODA0ZTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjJUMDczODU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjAyNjA5ZTRlNzJhNmI1YjA0NzZiOTk4MDI3OTQ2MzNjZWNkN2U2MTg0NWNlMWEwNGM3ZGMzMjAwMjQyN2QyNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.DrfJL_6GwGYIAgz5Av3xjRz3WjNI0Mew8EuFygxKZqc)

At the moment the filter is for every type of users, I've to change behavior by role

**Comment by leolami** [comment]
No we didn't understand each other

The filter must be based on Editor2 where you choose an Editor2 and find all the Groups associated with it
