### ISSUE TITLE
DEV on line: admin search project/group

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-admin#821]
### Checklist

- [ ] I've searched through the existing [issues](../issues) and this bug has never been reported before

### Subject of the issue

In ADMIN, the search to find projects or group doesn't work

### Steps to reproduce

You can try on DEV on line

### Environment

- g3w-admin: __3.8.g3w-client_PR574-20240419124935__

**Comment by wlorenzetti** [comment]
@leolami same search string example?

**Comment by Raruto** [comment]
@leolami Please create issues that are somehow reproducible by others.. 🥺

This problem lacks all the minimum information to follow it up, simply saying there is a bug is not helpful in tracking the problem (and the solution)

**NB** A link and a screenshot never hurts.

**Comment by leolami** [comment]
Sorry for the poor description

As seen yesterday, to find a project you need to write at least one word (COMPLETE) that appears in the project title

This makes searching complicated for the user

If possible I would say use a CONTAINS

If the matter is complex, we close the issue.
I will specify the behavior in the manual

**Comment by leolami** [comment]
Everything seems ok to me
