### ISSUE TITLE
Cache on layers doesn't work

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-admin#823]
### Checklist

- [x] I've searched through the existing [issues](../issues) and this bug has never been reported before

### Subject of the issue

The cache is created, apparently

But when I load the map the cache layer is not visible 

### Steps to reproduce

No need to reproduce the problem

### Environment

- g3w-admin: __version__
- g3w-client: __version__
- browser: __name__
- operating system: __name and version (desktop or mobile)__

**Comment by leolami** [comment]
@wlorenzetti  Confermo il problema, attivando la cache su un layer il progetto non si carica più

https://dev.g3wsuite.it/it/map/g3w-suite-demo/qdjango/97/

Cache sul layer ROADS

**Comment by Raruto** [comment]
@wlorenzetti has been fixed?
