### ISSUE TITLE
Update to 3.34 which is the new LTR as 3.28 is not supported anymore

### ISSUE THREAD

**Issue by tudorbarascu** [g3w-suite/g3w-admin#826]
### Checklist

- [X] I've searched through the [current issues](https://github.com/g3w-suite/g3w-admin/issues) to make sure this feature hasn't been requested already.

### Motivation

Some users migrate to 3.34 :)

### Suggested solution

Do the upgrade

**Comment by wlorenzetti** [comment]
Hi @tudorbarascu https://hub.docker.com/layers/g3wsuite/g3w-suite-deps-ltr/v3.7.x/images/sha256-4aed81b462b2f8c96f7d05287f80375868e977c0a0e3cd2c2aa07240fa54b2d7?context=explore

it's just on QGIS server 3.34.

**Comment by tudorbarascu** [comment]
Indeed! Thanks! Just checked! Sorry for the noise. :+1:
