### ISSUE TITLE
Credits

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-admin#84]
Replace the current info credits with:

**ENGLISH**
Application based on OS framework
G3WSUITE (logo con link https://g3wsuite.it)
Publish and manage your QGIS projects on the web

Framework developed by
GIS3W (logo con link https://gis3w.it)
Montecatini Terme (PT) - Italy
+39 393 8534336
+39 0572 901639
info@gis3w.it

---------------------------------------

**ITALIAN**
Applicazione basata sul framework OS
G3WSUITE (logo con link https://g3wsuite.it)
Pubblica e gestisci i tuoi progetti QGIS sul Web

Framework sviluppato da
GIS3W (logo con link https://gis3w.it)
Montecatini Terme (PT) - Italy
+39 393 8534336
+39 0572 901639
info@gis3w.it

**Comment by leolami** [comment]
@volterra79 la sostituzione fatta non è corretta, manca il logo di G3WSUITE (che c'era prima) ed i discorsini. Dato che ci siamo toglierei il fax

QUINDI RICAPITOLANDO:

ENGLISH
Application based on OS framework
G3WSUITE (logo con link https://g3wsuite.it)
Publish and manage your QGIS projects on the web

Framework developed by
GIS3W (logo con link https://gis3w.it)
Montecatini Terme - Italy
+39 393 8534336
info@gis3w.it

ITALIAN
Applicazione basata sul framework OS
G3WSUITE (logo con link https://g3wsuite.it)
Pubblica e gestisci i tuoi progetti QGIS sul Web

Framework sviluppato da
GIS3W (logo con link https://gis3w.it)
Montecatini Terme - Italy
+39 393 8534336
info@gis3w.it

**Comment by wlorenzetti** [comment]
@leolami can be closed?

**Comment by leolami** [comment]
@volterra79 puoi riverificare i contenuti dei credits?

Te li riallego

**Verifica che su mobile (smartphone) l'ultima parte dei credits viene spostata (e tagliata) sulla detra**
-----------------------------------------------------------

ENGLISH
Application based on OS framework
G3WSUITE (logo con link https://g3wsuite.it)
Publish and manage your QGIS projects on the web

Framework developed by
GIS3W (logo con link https://gis3w.it)
Montecatini Terme - Italy
+39 393 8534336
info@gis3w.it

ITALIAN
Applicazione basata sul framework OS
G3WSUITE (logo con link https://g3wsuite.it)
Pubblica e gestisci i tuoi progetti QGIS sul Web

Framework sviluppato da
GIS3W (logo con link https://gis3w.it)
Montecatini Terme - Italy
+39 393 8534336
info@gis3w.it
