### ISSUE TITLE
Filters/constraints icons and descriptions

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-admin#87]
**Geo Constraints:**
_Description:_ Manage editing geo-constaints
Icon:

**Alfanumeric constraints:**
_Description:_ Manage alphanumeric visualization and editing constraints
Icon:

**'New single constraints' button**
Replace description with 'New alphanumeric constraints'

**'Expression rules' icon**
_New icon:_ https://github.com/qgis/QGIS/blob/master/images/themes/default/mIconExpression.svg

**Comment by leolami** [comment]
Ho visto errori di traduzione messaggi
Te li riscrivo per un copia e incolla

**Icona dei Geo Constraints**
ENG: Manage editing geo-constaints
ITA: Gestisci geo-constraints su editing

**Icona dei filtri alfanumerici**
ENG: Manage alphanumeric visualization and editing constraints
ITA: Gestisci constraint alfanumerici su visualizzazione ed editing

L'icona che ti ho alleato va sostituita a questa
![immagine](https://user-images.githubusercontent.com/4012899/82642539-5d7a6900-9c0e-11ea-8bf9-b4b327c20f2c.png)

**Comment by leolami** [comment]
Altre cambi/traduzioni /aggiunte:

**EXPRESSION RULES**

Popup icona **Expression Rules**, modificare in:
ENG **QGIS Expression Rules**
ITA **Regole basate su espressioni di QGIS**

Finestra modale, modfica titolo ed aggiunta sottotitolo
ITA 
**Regole del vincolo basate su espressioni di QGIS**
Definisci, per ogni utente e/o gruppo di utenti, regole di visualizzazione/editing basate sulle espressioni di QGIS
ENG 
**Constraint Rules based on QGIS Expression**
Define, for each user and/or group of users, viewing/editing rules based on the QGIS expressions

---------------------------------------------------------------------------------------------

**SUBSET RULES**

Popup icona **Subset Rules** modificare in:
ENG **Provider's language / SQL dialect Rules**
ITS **Regole basate sul linguaggio o su SQL del provider**

Finestra modale, modfica titolo ed aggiunta sottotitolo
ITA
**Regole del vincolo basate su linguaggio o dialetto SQL del provider**
Definisci, per ogni utente e/o gruppo di utenti, regole di visualizzazione/editing basate su linguaggio o dialetto SQL in base al tipo di provider associato
ENG
**Constraint Rules based on provider's language / SQL dialect**
Define, for each user and/or group of users, viewing/editing rules based on the language or SQL dialect of the associated provider.

**Comment by wlorenzetti** [comment]
@leolami changed

**Comment by leolami** [comment]
All rigth!

Only one more things.

Replace SQL with QGIS expression in the relative forms

![immagine](https://user-images.githubusercontent.com/4012899/83137230-19dd9e80-a0e9-11ea-8ae0-056dcfe68f64.png)
