### ISSUE TITLE
Internal Server Error: when using QueryBuilder `IN` / `NOT IN` clauses

### ISSUE THREAD

**Issue by Raruto** [g3w-suite/g3w-admin#874]
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-admin/issues) and this bug has never been reported before

### Subject of the issue

`IN` and `NOT IN` clauses appear to be unsupported, same behavior also with v37.

## POST: `{"field":"name NOT|IN|('Blue%20Palace')","formatter":1}`

![image](https://github.com/g3w-suite/g3w-admin/assets/9614886/1fb2067c-cc04-41c3-b5a4-2bc10ba31591)

## POST: `{"field":"name|IN|('Blue%20Palace')","formatter":1}`

![image](https://github.com/g3w-suite/g3w-admin/assets/9614886/83fac58c-decd-441e-89f3-285b5bf87127)

### Environment

 [g3wsdk.info]

- g3w-admin: __v3.6.24__
- g3w-client: __3.8.17__
- browser: __Firefox 126.0__
- operating system: __Windows 11 64-bit__

### Link to your project

https://v36.g3wsuite.it/vector/api/data/qdjango/97/buildings_2f43dc1d_6725_42d2_a09b_dd446220104a/

**Comment by wlorenzetti** [comment]
@Raruto following the comparators available:
```python
COMPARATORS_MAP = {
        'eq': '=',
        'gt': '>',
        'lt': '<',
        'ltgt': '<>',
        'gte': '>=',
        'lte': '<=',
        'like': 'LIKE',
        'ilike': 'ILIKE',
        'in': 'IN'
    }
```
So per `IN` try with `in` (lowercase)

`NOT IN` it desn't  exist, I'll try to add.

**Comment by Raruto** [comment]
> So per IN try with in (lowercase)

@wlorenzetti If feasable, please also add support for case-insensitive operators (http client-side code is not very clear in here).

---

How it should work in case of multiple values?

**OK:**

https://v37.g3wsuite.it/vector/api/data/qdjango/97/buildings_2f43dc1d_6725_42d2_a09b_dd446220104a/?field=name|in|('Blue%20Palace')&formatter=1

**KO:** `Invalid field string supplied for parameter field`

https://v37.g3wsuite.it/vector/api/data/qdjango/97/buildings_2f43dc1d_6725_42d2_a09b_dd446220104a/?field=name|in|('Blue%20Palace','Ice%20Palace')&formatter=1
