### ISSUE TITLE
Active Directory integration (LDAP Users)

### ISSUE THREAD

**Issue by AlexGacon** [g3w-suite/g3w-admin#878]
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-admin/issues) and this bug has never been reported before

### Subject of the issue

I am looking on how to enable a LDAP authN backend as stated by the documentation.

In the codebase I have some references on authldap module but I cannot find it anywhere. Where is it available?

### Steps to reproduce

No steps, question only

### Environment

Checked in main branch

**Comment by Raruto** [comment]
Hi @AlexGacon,

if you added some references to your statements it wouldn't hurt 😉, eg:

> I am looking on how to enable a LDAP authN backend as stated by the documentation.

👉 https://g3w-suite.readthedocs.io/en/latest/g3wsuite_administration.html#users-list

> In the codebase I have some references on authldap module but I cannot find it anywhere. Where is it available?

👉 https://github.com/search?q=repo%3Ag3w-suite%2Fg3w-admin%20ldap&type=code

> No steps, question only

Next time, it would be also better to ask that on:  [community/discussions](https://github.com/g3w-suite/community/discussions)

---

In any case, this statement:

> The Suite is equipped with a dedicated module for the integration of Active Directory users via LDAP.

It should refer to a dedicated plugin (from a private repo) that's installed at customers' premises.

If you are interested in learning more, try contacting sales department at info@gis3w.it

👋 Raruto

**Comment by AlexGacon** [comment]
Hello Raruto. Sorry for the noise, I wasn't aware of the availability of the discussion function!
