### ISSUE TITLE
Table fields order

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-admin#883]
### Checklist

- [x] I've searched through the [current issues](https://github.com/g3w-suite/g3w-admin/issues) to make sure this feature hasn't been requested already.

### Motivation

Defining the order of fields in the table is very useful

### Suggested solution

Manage the order of fields based on the related settings deriving from the QGIS project

The order must be show also in the editing mode

**Comment by Raruto** [comment]
same as: https://github.com/g3w-suite/g3w-admin/issues/928
