### ISSUE TITLE
Allow to store into layer the group associated with the editing user 

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-admin#885]
### Checklist

- [x] I've searched through the [current issues](https://github.com/g3w-suite/g3w-admin/issues) to make sure this feature hasn't been requested already.

### Motivation

When saving a geometry, it must be possible not only to save, at record level, the creator/modifier user, but also the reference to the group of users to which the editing user belongs

### Suggested solution

Replicate the current admin/client flow relating to setting up and saving editor user

**Comment by wlorenzetti** [comment]
@leolami user can belong to many group of users, I have to save a comma separated list of this groups, It could be ok?

**Comment by leolami** [comment]
Yes, it could be a solution

**Comment by leolami** [comment]
@wlorenzetti suspend the creation of this feature until further notice
