### ISSUE TITLE
Allow to configure superuser account from environment variables

### ISSUE THREAD

**Issue by AlexGacon** [g3w-suite/g3w-admin#889]
### Checklist

- [X] I've searched through the [current issues](https://github.com/g3w-suite/g3w-admin/issues) to make sure this feature hasn't been requested already.

### Motivation

For automatic deployment on kubernetes cluster, I need to be able to inject in the solution a custom superuser account and a custom default password which can be store either as Secrets in K8s or as GitLab secrets for example.

### Suggested solution

A solution could be to amend the setup_suite.sh file to use environment variables instead of the hard coded values.

**Comment by wlorenzetti** [comment]
@AlexGacon thanks for the suggestion, I'm curios do you have some G3W-SUITE instance on kubernetes to look at?

**Comment by AlexGacon** [comment]
I am working on it but it won't be publicly available.

@wlorenzetti I will be at FOSS4G EU next week if you want to discuss this.

**Comment by wlorenzetti** [comment]
See you in Tartu!

**Comment by Raruto** [comment]
Related code:

https://github.com/g3w-suite/g3w-admin/blob/b7ffb5dcd7dd839333db52a1a00da8edc71aa6c7/ci_scripts/setup_suite.sh#L74

https://github.com/g3w-suite/g3w-admin/blob/b7ffb5dcd7dd839333db52a1a00da8edc71aa6c7/g3w-admin/base/management/commands/initadmin.py#L7-L20

**Comment by AlexGacon** [comment]
@Raruto for setup_suite.sh isn't it the line bellow which is interesting?

**Comment by AlexGacon** [comment]
@wlorenzetti @Raruto I hope the 3 PRs are fine for you.
