### ISSUE TITLE
"Layer error on datasource" when trying to upload a new QGIS project

### ISSUE THREAD

**Issue by subhash85-GIS** [g3w-suite/g3w-admin#891]
### Checklist

- [ ] I've searched through the [current issues](https://github.com/g3w-suite/g3w-admin/issues) to make sure this feature hasn't been requested already.

### Motivation

<img width="950" alt="Error_While uploading Project" src="https://github.com/g3w-suite/g3w-admin/assets/173986831/55ac4134-cc0b-4415-ae03-6b1a9ba2643e">
We are getting errors while uploading Projects in G3W 
The CRS WGS 84 EPSG 4326 Projection is not allow to G3W

<img width="950" alt="Error_While uploading Project" src="https://github.com/g3w-suite/g3w-admin/assets/173986831/9968474a-5f0b-404a-a66d-3893bbc5d419">

### Suggested solution

NA

**Comment by wlorenzetti** [comment]
Hi @subhash85-GIS did you upload `Fiber_V1,shp` by the file manager?

**Comment by subhash85-GIS** [comment]
I was trying to upload the project, and three shape files were incorporated into that project.

**Comment by leolami** [comment]
Hi @subhash85-GIS 

read this pargraph of the manual to understand how organize projects and data in local and in the server

https://g3w-suite.readthedocs.io/en/v3.8.x/datamanagement.html

**Comment by wlorenzetti** [comment]
> I was trying to upload the project, and three shape files were incorporated into that project.

What's mean `incorporated` ?

You have to upload the shape file before to upload the project on filemanger section:
![Screenshot_20240627_083944](https://github.com/g3w-suite/g3w-admin/assets/196809/71fe84f2-7dd5-43d0-935c-cc870cdc3643)

![Screenshot_20240627_084003](https://github.com/g3w-suite/g3w-admin/assets/196809/736dbf5c-722e-431a-b3d9-260f4f62ec5a)

**Comment by subhash85-GIS** [comment]
Thanks For the support  
Would you please let me know the below question
1) Does this allow G3W projection EPSG 4326?
2)What is the step for new Project creation from the File manager as suggested earlier

**Comment by subhash85-GIS** [comment]
Thanks for the support  👍 
Issue is resolved
