### ISSUE TITLE
Use english as fallback language

### ISSUE THREAD

**Issue by AlexGacon** [g3w-suite/g3w-admin#892]
### Checklist

- [X] I've searched through the [current issues](https://github.com/g3w-suite/g3w-admin/issues) to make sure this feature hasn't been requested already.

### Motivation

When I use a language with a partial translation (for example French), G3W uses the Italian text as placeholder when a text is not translated.

### Suggested solution

Having a fallback to English would make G3W easier to use and start with for non Italian speaker.

**Comment by wlorenzetti** [comment]
@AlexGacon just set `LANGUAGE_CODE = 'en'` into the settings.

**Comment by AlexGacon** [comment]
@wlorenzetti it works as expected. Do you want to keep italian as default language in the repo?

**Comment by Raruto** [comment]
I agree with @AlexGacon,

FYI, English is the fallback language within frontend code: [g3w-client/src/app/core/i18n/i18n.service.js#L17](https://github.com/g3w-suite/g3w-client/blob/3b20da26f0b10eea2327715fd3cc9e44a9082867/src/app/core/i18n/i18n.service.js#L17)
