### ISSUE TITLE
Add https://github.com/g3w-suite/g3w-client/commit/30c41557cecf2f7781d0c5d4b8efeed0771987fd fix to v3.8.x branch

### ISSUE THREAD

**Issue by tudorbarascu** [g3w-suite/g3w-admin#900]
### Checklist

- [X] I've searched through the [current issues](https://github.com/g3w-suite/g3w-admin/issues) to make sure this feature hasn't been requested already.

### Motivation

Hello! I got hit by the above bug so it would be nice if that would be backported to v3.8.x branch

### Suggested solution

https://github.com/g3w-suite/g3w-client/commit/30c41557cecf2f7781d0c5d4b8efeed0771987fd should be backported to v.3.8.x branch

**Comment by wlorenzetti** [comment]
Hi @tudorbarascu we will backport it in the nexst v3.8.x release.

**Comment by tudorbarascu** [comment]
Thank you!
