### ISSUE TITLE
Hide columns by User/Groups doesn't works in editing mode

### ISSUE THREAD

**Issue by gisuser0** [g3w-suite/g3w-admin#916]
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-admin/issues) and this bug has never been reported before

### Subject of the issue

With the "Hide columns by User/Groups" function it's possible to hide specific fields of a layer.
It works with the info form and the attribute table but when the layer is in editing mode, the specific fields are visible and editable in the editing form.

### Steps to reproduce

1. Use the project of the online demo [(https://g3wsuite.it/demo_3-8/)](https://g3wsuite.it/demo_3-8/)
2. Create a new user "user1" and hide the field "address" of the layer "buildings" for this user

![image](https://github.com/user-attachments/assets/1756ed4c-589f-4ba9-9fa8-55a6619349ca)

![image](https://github.com/user-attachments/assets/f2ba0594-4ef5-479b-b73f-aa4d818ab500)

3. Query the layer logged as superuser: the field "address" is visible

![image](https://github.com/user-attachments/assets/454f6fa9-29ae-4e4a-ac54-0412a5696898)

4. Query the layer logged as "user1": the field "address" is not visible

![image](https://github.com/user-attachments/assets/26b1d44a-d35d-4a69-9f7b-fce1b0d85a74)

5: Start the editing with the "user1": the field "address" is now visible and editable

![image](https://github.com/user-attachments/assets/d1209ef0-21e3-43af-96d1-56d8ed71d8b6)

### Environment

- g3w-admin: 3.8.dev-20240605113156
- g3w-client: 3.10.0
- editing: 3.8.0
- qtimeseries: 3.8.0-alpha.0
- browser: Chrome 126.0.0.0
- operating system: Linux 64-bit

**Comment by Raruto** [comment]
Hi @gisuser0, thanks for the report.

> ### Steps to reproduce
> 1. hide some fields of a layer for a specific user/groups
> 2. start the editing on that layer: the fields set as hidden are visible and editable


Please also add some self-explanatory images in the first comment to support debugging (ie. anyone else should understand this, not just core developers..).

👋 Raruto

**Comment by Raruto** [comment]
I think we are getting a bad server response (ref: `editor_form_structure` within initial config)

## • Foo: `Editor Level 1`

![image](https://github.com/user-attachments/assets/4076268d-c2ad-435a-84b1-5f0be2b0946b)

## • localhost:8000/api/config/1/qdjango/1?_t=1721996359.094077

- `layers → fields`:

![image](https://github.com/user-attachments/assets/f29aa605-a7a8-46a3-981d-9362745d3292)

- `layers → editor_form_structure`:

![image](https://github.com/user-attachments/assets/693a24d0-61e5-4582-b2d5-ff30d3546fc4)

👋 Raruto
