### ISSUE TITLE
Conditional group

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-admin#932]
### Checklist

- [x] I've searched through the existing [issues](../issues) and this bug has never been reported before

### Subject of the issue

I have a conditional group of field where the visibility is based on a boolean field and the expression is "field IS FALSE"

By default the field is setted FALSE but to see the condition fields group I have to set the boolean field TRUE and then FALSE

### Steps to reproduce

http://irpi.cnr.schede-siti.g3wsuite.it/it/map/irpi-schede-siti/qdjango/2/

Create a new SITI DI ANALISI and look at boolean field named **transabilita** (alias: Strada di accesso transitabile con mezzi pesanti *)

At the start
![Image](https://github.com/user-attachments/assets/e12b1e43-0dbf-4b22-9762-4ba5d6a2f791)

After switch TRUE and FALSE

![Image](https://github.com/user-attachments/assets/4ec9c464-8fef-411e-b29f-f81b7a6b8073)

### Environment

- g3w-admin: __v3.8.1__
- g3w-client: __3.10.2__
    - editing: __3.8.2__
    - qtimeseries: __3.8.0__
- browser: __Firefox 131.0__
- operating system: __Linux 64-bit__

### Link to your project

http://irpi.cnr.schede-siti.g3wsuite.it/it/map/irpi-schede-siti/qdjango/2/

**Comment by volterra79** [comment]
@leolami need to check with @wlorenzetti . It seems that response from server is the issue

**Comment by volterra79** [comment]
@wlorenzetti il problema è nel default value per i widget **check**.

**Comment by leolami** [comment]
Allora anche in QGIS la cosa non funziona se si parte diretamente dal figlio

La mia domanda è:

Te puoi sapere se per un layer esistono una o più relazioni (di cui il layer è figlio) e conoscerne i padri?

Potrebbe aver senso applicare l'espressione (current_parent_value) solo nel caso esista UNA SOLA relazione?

**Comment by volterra79** [comment]
> Allora anche in QGIS la cosa non funziona se si parte diretamente dal figlio
> 
> La mia domanda è:
> 
> Te puoi sapere se per un layer esistono una o più relazioni (di cui il layer è figlio) e conoscerne i padri?
> 
> Potrebbe aver senso applicare l'espressione (current_parent_value) solo nel caso esista UNA SOLA relazione?

@leolami io posso sapere se il figlio se ha più relazioni. Per la seconda parte, secondo em dovrebbe essere gestita a livello QGIS. Significa che chi fa il progetto mette quell'espressione solo se c'è una sola relazione. Comunque questa cosa si ha solo sull'upadte non sull'insert giusto?

**Comment by leolami** [comment]
I'm testing on v.3.8.x-20240927125322

But this probelm is ever present...

We can test on teh same projects above where @wlorenzetti have update with v.3.8.x-20240927125322

**Comment by leolami** [comment]
@volterra79 ho pubblicato questo come richiesto e mi sembra tutto a posto

https://dev.g3wsuite.it/it/map/g3w-suite-demo/qdjango/284/

Se vuoi provare, poi portiamo su 3.8.2

**Comment by wlorenzetti** [comment]
@volterra79 can be closed this issue?
