### ISSUE TITLE
Editing: set editable layers not viewable

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-admin#956]
### Checklist

- [x] I've searched through the [current issues](../issues) to make sure this feature hasn't been requested already.

### Motivation

We often manage projects with one or more layers with many editable 1:N relationships

For the workflow, however, it would not be correct to have the possibility to enter editing directly on the child layers of the relationship but to access editing only starting from the parent

### Suggested solution

An option that allows you to define whether or not the layer being edited is visible in the list of editable layers could be useful

While it is easier when you define the activation level editing option on individual layers it may be more complicated when using the multi-layer editing tool

**Comment by volterra79** [comment]
@wlorenzetti need a way to get this information from server/plugin config.
@leolami waht about edit feature (pencil icon on result) for the layer that was set not visible on editing panel?

**Comment by leolami** [comment]
Pencil NOT visibile on query results form

**Comment by volterra79** [comment]
@wlorenzetti we can use /vector/api/config/qdjango/50/<LAYER_ID>/ api

```
{
    "result": true,
    "vector": {
        "format": "GeoJSON",
        "count": null,
        "data": null,
        "geometrytype": "NoGeometry",
        "fields": [
            {
                "name": "fid",
                "type": "bigint",
                "label": "Intervention ID",
                "editable": false,
                "validate": {
                    "required": true,
                    "unique": true
                },
                "pk": true,
                "default": "Autogenerate",
                "input": {
                    "type": "text",
                    "options": {}
                }
            },
            .....
        ]
    },
    "featurelocks": null,
    "constraints": {},
    "visible":       <BOOLEAN> // default true
    "capabilities": [
        "add_feature",
        "change_feature",
        "delete_feature",
        "change_attr_feature"
    ]
}
```

add **"visible":**       <BOOLEAN> // default true attribute

**Comment by leolami** [comment]
This option must also be managed at the multilayer editing activation level

Thank you

**Comment by leolami** [comment]
@volterra79 
 
1. Load the map https://dev.g3wsuite.it/it/map/g3w-suite-demo/qdjango/97/
2. Go on Editing -> You don't see the  Buildings rating layer in the list -> **OK**
3. Close editing
4. Go a new time on Editing -> Now you see the  Buildings rating layer in the list -> **KO**

**Comment by volterra79** [comment]
@leolami i'll check

**Comment by volterra79** [comment]
@leolami fixed
