### ISSUE TITLE
Error on PDF download

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-admin#962]
### Checklist

- [x] I've searched through the existing [issues](../issues) and this bug has never been reported before

### Subject of the issue

There is an error when I try to download the attribute info in PDF

![Image](https://github.com/user-attachments/assets/c5bd2065-264f-4a17-9e2c-18265296d4d9)

### Steps to reproduce

https://dev.g3wsuite.it/it/map/g3w-suite-demo/qdjango/97/

1. Click on a buildings
2. Click on the download icon in the attribute form
3. Chooes PDF format
4. Download it

### Environment

3.8.save_user_group_on_editing-20241022075334

### Link to your project

https://dev.g3wsuite.it/it/map/g3w-suite-demo/qdjango/97/

**Comment by wlorenzetti** [comment]
Fixed by https://github.com/g3w-suite/g3w-admin/commit/cfe328dcb3368d449b0693750378a5defef081ea
