### ISSUE TITLE
Hide "open attribute table" entry for WMS layers (context menu)

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-admin#964]
### Checklist

- [x] I've searched through the existing [issues](../issues) and this bug has never been reported before

### Subject of the issue

This entry should only be available for:
- geometric vector data
- alphanumeric tables

Must not be available for:
- raster data
- dat WMS (as per example)

![Image](https://github.com/user-attachments/assets/405a15fc-d8dc-4309-b313-d0f103d6a106)

### Steps to reproduce

Open context menù layer ofa WMS layer

### Environment

 [g3wsdk.info]

- g3w-admin: __3.8.dev-20241022075046__
- g3w-client: __3.11.0-alpha.1__
    - editing: __3.9.0-alpha.0__
    - qtimeseries: __3.8.0__
- browser: __Firefox 131.0__
- operating system: __Windows 10 64-bit__

### Additional info

3.8.dev-20241018150811

**Comment by Raruto** [comment]
> ### Link to your project
> 
> _No response_

@leolami where did you find that?

**Comment by leolami** [comment]
You can see the problem here

http://db.irpi.cnr.schede-siti.g3wsuite.it/it/map/irpi-schede-siti/qdjango/2/

Try to open the context menù on Ortofotos layers as in the image

Ortofotos are WMS layers

**Comment by Raruto** [comment]
@wlorenzetti For those wms levels, you should set this value as default:

```js
not_show_attribute_tables: true
```

![image](https://github.com/user-attachments/assets/93f6d8fb-8ac0-4498-a699-5435e5fbbce9)

![image](https://github.com/user-attachments/assets/9f378178-6d90-430f-a25a-b2aa84c12ecf)

Rif:

- http://db.irpi.cnr.schede-siti.g3wsuite.it/it/map/irpi-schede-siti/qdjango/2/
- http://db.irpi.cnr.schede-siti.g3wsuite.it/api/config/1/qdjango/2
