### ISSUE TITLE
Editing: attached file icon

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-admin#97]
When I upload a multimedial file I can see the right icon associtaed (image or pdf icon)

Some time, when I modify the same feature, I see **?** icon
![immagine](https://user-images.githubusercontent.com/4012899/82992958-2a661a00-a000-11ea-80e2-59a9f1a344ff.png)

I would expect this icon to be shown when:
- the attached file is not an image or a pdf
- when the file does not exist

Can you check?

**Comment by wlorenzetti** [comment]
@leolami you look at this behavior on editing of existing feature on a  new uploading test?
Now on dev server media and photo missing can appear with a 'question mark' icon.

**Comment by leolami** [comment]
It appears on editing of existing feature, also if before I attached correctly image or pdf at the same feature

You can test on Public Buildings **Edificio Blu**

**Comment by wlorenzetti** [comment]
I don't know the problem but now for is working right.
