### ISSUE TITLE
Geopackage editing

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-admin#98]

**Comment by leolami** [comment]
http://64.225.77.93:8080/it/map/g3w-suite-demo/qdjango/5/

Try to edit the alphanumeric layer (**INFO**) adding one new features or modifing one

When you try to insert **date** you have a clock widget and not a calendar widget
The field **date** is a DATE type

All work right if you edit the other layer that have field DATE type

**Comment by leolami** [comment]
@leolami check display format in QGIS project

**Comment by leolami** [comment]
Type of field and display format of the field _DATE_ of layer INFO (alphanumeric) are the same of the other layer (POLIGONI and TEST).

When you edit layer POLIGONI or TEST we have **calendar widget** (RIGHT)
While when you edit layer INFO we have **clock widget** (WRONG)

@wlorenzetti can you check with @volterra79 ?

**Comment by wlorenzetti** [comment]
@leolami it was fixed.

**Comment by leolami** [comment]
http://64.225.77.93:8080/it/map/g3w-suite-demo/qdjango/5/

Se provi a modificare i dati associati ad un poligono quando salvi da errore

**Comment by leolami** [comment]
Bug linked managment of join
Resolved
